# Install Java

In [ ]:
#!apt-get install openjdk-8-jdk
!apt-get install default-jre

In [2]:
!java -version # This command displays Java version.

openjdk version "11.0.22" 2024-01-16
OpenJDK Runtime Environment (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1)
OpenJDK 64-Bit Server VM (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1, mixed mode, sharing)

# Install H2O

In [ ]:
!pip install H2O

In [4]:
import h2o
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "11.0.22" 2024-01-16; OpenJDK Runtime Environment (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1); OpenJDK 64-Bit Server VM (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.10/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmph4wpp8bv
  JVM stdout: /tmp/tmph4wpp8bv/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmph4wpp8bv/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         03 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.2
H2O_cluster_version_age:    20 days
H2O_cluster_name:           H2O_from_python_unknownUser_v7g90w
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.170 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.10.12 final
--------------------------  -----------------------------------------------------------------------------------------

In [5]:
h2o.cluster().show_status() # Check the status and health of the H2O cluster

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         1 min 17 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.2
H2O_cluster_version_age:    20 days
H2O_cluster_name:           H2O_from_python_unknownUser_v7g90w
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.170 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.10.12 final
--------------------------  -----------------------------------------------------------------------------------------

# Tunel to localhost

In [6]:
!npm install -g localtunnel

⠙⠹⠸⠼⠴⠦⠧⠇⠏⠋⠙⠹⠸⠼⠴⠦⠧⠇
added 22 packages in 2s
⠇
⠇3 packages are looking for funding
⠇  run `npm fund` for details
⠇

In [7]:
get_ipython().system_raw('lt --port 54321 >> url.txt &')

In [8]:
!cat url.txt

your url is: https://all-bats-relate.loca.lt

In [9]:
!curl https://loca.lt/mytunnelpassword

150.254.68.63

# Data Preparation and simple statistics
Although it may seem like you are manipulating the data in Python, once the
data has been passed to H2O, all data munging occurs in the H2O
instance. You are limited by the total amount of memory allocated to the H2O
instance, not by Python's ability to handle data.

In [ ]:
airlinesURL = 'https://raw.githubusercontent.com/h2oai/h2o-tutorials/refs/heads/master/tutorials/data/allyears2k.csv' # File path
# The U.S. Department of Transportation's (DOT) Bureau of Transportation Statistics (BTS)
# tracks the on-time performance of domestic flights operated by large air carriers.

airlines_hex = h2o.import_file(airlinesURL, destination_frame = 'airlines_hex')
airlines_hex.head()

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

  Year    Month    DayofMonth    DayOfWeek    DepTime    CRSDepTime    ArrTime    CRSArrTime  UniqueCarrier      FlightNum  TailNum      ActualElapsedTime    CRSElapsedTime    AirTime    ArrDelay    DepDelay  Origin    Dest      Distance    TaxiIn    TaxiOut    Cancelled  CancellationCode      Diverted    CarrierDelay    WeatherDelay    NASDelay    SecurityDelay    LateAircraftDelay  IsArrDelayed    IsDepDelayed
------  -------  ------------  -----------  ---------  ------------  ---------  ------------  ---------------  -----------  ---------  -------------------  ----------------  ---------  ----------  ----------  --------  ------  ----------  --------  ---------  -----------  ------------------  ----------  --------------  --------------  ----------  ---------------  -------------------  --------------  --------------
  1987       10            14            3        741           730        912           849  PS                      1451  NA                          91                79        nan          23          11  SAN       SFO            447       nan        nan            0  NA                           0             nan             nan         nan              nan                  nan  YES             YES
  1987       10            15            4        729           730        903           849  PS                      1451  NA                          94                79        nan          14          -1  SAN       SFO            447       nan        nan            0  NA                           0             nan             nan         nan              nan                  nan  YES             NO
  1987       10            17            6        741           730        918           849  PS                      1451  NA                          97                79        nan          29          11  SAN       SFO            447       nan        nan            0  NA                           0             nan             nan         nan              nan                  nan  YES             YES
  1987       10            18            7        729           730        847           849  PS                      1451  NA                          78                79        nan          -2          -1  SAN       SFO            447       nan        nan            0  NA                           0             nan             nan         nan              nan                  nan  NO              NO
  1987       10            19            1        749           730        922           849  PS                      1451  NA                          93                79        nan          33          19  SAN       SFO            447       nan        nan            0  NA                           0             nan             nan         nan              nan                  nan  YES             YES
  1987       10            21            3        728           730        848           849  PS                      1451  NA                          80                79        nan          -1          -2  SAN       SFO            447       nan        nan            0  NA                           0             nan             nan         nan              nan                  nan  NO              NO
  1987       10            22            4        728           730        852           849  PS                      1451  NA                          84                79        nan           3          -2  SAN       SFO            447       nan        nan            0  NA                           0             nan             nan         nan              nan                  nan  YES             NO
  1987       10            23            5        731           730        902           849  PS                      1451  NA                          91                79        nan          13           1  SAN       SFO            447       nan        nan            0  NA                           0             nan             nan         nan              nan                  nan  YES             YES
  1987       10            24            6        744           730        908           849  PS                      1451  NA                          84                79        nan          19          14  SAN       SFO            447       nan        nan            0  NA                           0             nan             nan         nan              nan                  nan  YES             YES
  1987       10            25            7        729           730        851           849  PS                      1451  NA                          82                79        nan           2          -1  SAN       SFO            447       nan        nan            0  NA                           0             nan             nan         nan              nan                  nan  YES             NO
[10 rows x 31 columns]

In [ ]:
# Summary statistics
airlines_hex.describe()

Rows:43978
Cols:31

         Year               Month               DayofMonth          DayOfWeek           DepTime             CRSDepTime          ArrTime             CRSArrTime          UniqueCarrier    FlightNum          TailNum    ActualElapsedTime    CRSElapsedTime      AirTime             ArrDelay            DepDelay            Origin    Dest    Distance           TaxiIn             TaxiOut             Cancelled             CancellationCode    Diverted               CarrierDelay       WeatherDelay         NASDelay           SecurityDelay         LateAircraftDelay    IsArrDelayed    IsDepDelayed
-------  -----------------  ------------------  ------------------  ------------------  ------------------  ------------------  ------------------  ------------------  ---------------  -----------------  ---------  -------------------  ------------------  ------------------  ------------------  ------------------  --------  ------  -----------------  -----------------  ------------------  --------------------  ------------------  ---------------------  -----------------  -------------------  -----------------  --------------------  -------------------  --------------  --------------
type     int                int                 int                 int                 int                 int                 int                 int                 enum             int                enum       int                  int                 int                 int                 int                 enum      enum    int                int                int                 int                   enum                int                    int                int                  int                int                   int                  enum            enum
mins     1987.0             1.0                 1.0                 1.0                 1.0                 0.0                 1.0                 0.0                                  1.0                           16.0                 17.0                14.0                -63.0               -16.0                                 11.0               0.0                0.0                 0.0                                       0.0                    0.0                0.0                  0.0                0.0                   0.0
mean     1997.5             1.4090909090909092  14.601073263904679  3.8206148528809867  1345.8466613820763  1313.2228614307153  1504.6341303788888  1485.2891673109286                   818.8429896766565             124.8145291354042    125.02156260661893  114.31611109078267  9.317111936984317   10.007390655600114                    730.1821905650502  5.381368059530624  14.168634184732056  0.024694165264450407                      0.0024785119832643593  4.047800291055638  0.28937646927124144  4.855031904175531  0.017015560282100085  7.620060450016793
maxs     2008.0             10.0                31.0                7.0                 2400.0              2359.0              2400.0              2359.0                               3949.0                        475.0                437.0               402.0               475.0               473.0                                 3365.0             128.0              254.0               1.0                                       1.0                    369.0              201.0                323.0              14.0                  373.0
sigma    6.344360901710633  1.874711371343963   9.17579042586145    1.9050131191328967  465.3408991242339   476.25113999259975  484.34748790351597  492.75043412270105                   777.4043691636348             73.97444166059017    73.40159463000928   69.63632951506105   29.840221962414844  26.43880904291645                     578.4380082304243  4.201979939864828  9.905085747204325   0.15519314135784237                       0.049723487218862286   16.2057299044842   4.416779898734125    18.61977622147568  0.40394018210151184   23.487565874106213
zeros    0                  0                   0                   0                   0                   569                 0                   569                                  0                             0                    0                   0                   1514                6393                                  0                  623                557                 42892                                     43869                  7344               8840                 7388               8914                  7140
missing  0                  0                   0                   0                   1086                0                   1195                0                   0                0                  32         1195                 13                  16649               1195                1086                0         0       35                 16026              16024               0                     9774                0                      35045              35045                35045              35045                 35045                0               0
0        1987.0             10.0                14.0                3.0                 741.0               730.0               912.0               849.0               PS               1451.0             NA         91.0                 79.0                nan                 23.0                11.0                SAN       SFO     447.0              nan                nan                 0.0                   NA                  0.0                    nan                nan                  nan                nan                   nan                  YES             YES
1        1987.0             10.0                15.0                4.0                 729.0               730.0               903.0               849.0               PS               1451.0             NA         94.0                 79.0                nan                 14.0                -1.0                SAN       SFO     447.0              nan                nan                 0.0                   NA                  0.0                    nan                nan                  nan                nan                   nan                  YES             NO
2        1987.0             10.0                17.0                6.0                 741.0               730.0               918.0               849.0               PS               1451.0             NA         97.0                 79.0                nan                 29.0                11.0                SAN       SFO     447.0              nan                nan                 0.0                   NA                  0.0                    nan                nan                  nan                nan                   nan                  YES             YES
3        1987.0             10.0                18.0                7.0                 729.0               730.0               847.0               849.0               PS               1451.0             NA         78.0                 79.0                nan                 -2.0                -1.0                SAN       SFO     447.0              nan                nan                 0.0                   NA                  0.0                    nan                nan                  nan                nan                   nan                  NO              NO
4        1987.0             10.0                19.0                1.0                 749.0               730.0               922.0               849.0               PS               1451.0             NA         93.0                 79.0                nan                 33.0                19.0                SAN       SFO     447.0              nan                nan                 0.0                   NA                  0.0                    nan                nan                  nan                nan                   nan                  YES             YES
5        1987.0             10.0                21.0                3.0                 728.0               730.0               848.0               849.0               PS               1451.0             NA         80.0                 79.0                nan                 -1.0                -2.0                SAN       SFO     447.0              nan                nan                 0.0                   NA                  0.0                    nan                nan                  nan                nan                   nan                  NO              NO
6        1987.0             10.0                22.0                4.0                 728.0               730.0               852.0               849.0               PS               1451.0             NA         84.0                 79.0                nan                 3.0                 -2.0                SAN       SFO     447.0              nan                nan                 0.0                   NA                  0.0                    nan                nan                  nan                nan                   nan                  YES             NO
7        1987.0             10.0                23.0                5.0                 731.0               730.0               902.0               849.0               PS               1451.0             NA         91.0                 79.0                nan                 13.0                1.0                 SAN       SFO     447.0              nan                nan                 0.0                   NA                  0.0                    nan                nan                  nan                nan                   nan                  YES             YES
8        1987.0             10.0                24.0                6.0                 744.0               730.0               908.0               849.0               PS               1451.0             NA         84.0                 79.0                nan                 19.0                14.0                SAN       SFO     447.0              nan                nan                 0.0                   NA                  0.0                    nan                nan                  nan                nan                   nan                  YES             YES
9        1987.0             10.0                25.0                7.0                 729.0               730.0               851.0               849.0               PS               1451.0             NA         82.0                 79.0                nan                 2.0                 -1.0                SAN       SFO     447.0              nan                nan                 0.0                   NA                  0.0                    nan                nan                  nan                nan                   nan                  YES             NO
[43978 rows x 31 columns]

In [12]:
# Quantiles of the ArrDelay column
quantiles = airlines_hex['ArrDelay'].quantile(prob = [0.25, 0.5, 0.75, 1.0])
print(quantiles)

  Probs    ArrDelayQuantiles
   0.25                   -6
   0.5                     2
   0.75                   14
   1                     475
[4 rows x 2 columns]

In [13]:
# Histogram of the ArrDelay column
airlines_hex['ArrDelay'].hist()

    breaks    counts    mids_true      mids    widths
----------  --------  -----------  --------  --------
-31.3529         nan        nan    nan       nan
  0.294118       173        -31.5  -15.5294   31.6471
 31.9412       19364        -15.5   16.1176   31.6471
 63.5882       18089          0.5   47.7647   31.6471
 95.2353        3163         16     79.4118   31.6471
126.882         1067         32    111.059    31.6471
158.529          444         48    142.706    31.6471
190.176          221         63.5  174.353    31.6471
221.824          116         79.5  206        31.6471
253.471           60         95.5  237.647    31.6471
[17 rows x 5 columns]

In [14]:
# Check if any column is a factor
any(airlines_hex.type(col) == 'enum' for col in airlines_hex.names)

True

In [15]:
# Group by 'Origin' and calculate the number of rows, removing NA values
airlines_hex.group_by('Origin').count(na='rm').get_frame()

Origin      nrow
--------  ------
ABE           59
ABQ          876
ACY           31
ALB           75
AMA           11
ANC            1
ATL          754
AUS          835
AVP          154
BDL          141
[132 rows x 2 columns]

In [16]:
# Group by 'Month' and calculate the number of rows, removing NA values
airlines_hex.group_by('Month').count(na='rm').get_frame()

  Month    nrow
-------  ------
      1   41979
     10    1999
[2 rows x 2 columns]

In [17]:
# Group by 'Month' and calculate the number of cancellations, removing NA values
cancellations_by_month = airlines_hex.group_by('Month').sum('Cancelled', na='rm').get_frame()
print(cancellations_by_month)

# Group by 'Month' and calculate the number of flights, removing NA values
flights_by_month = airlines_hex.group_by('Month').count(na='rm').get_frame()
print(flights_by_month)

# Calculate cancellation rate
cancellation_rate = cancellations_by_month['sum_Cancelled'] / flights_by_month['nrow']
print(cancellation_rate)

# Combine month and cancellation rate into a single table
rates_table = flights_by_month.cbind(cancellation_rate)
rates_table.set_name(2, 'Cancellation_Rate')
print(rates_table)

  Month    sum_Cancelled
      1             1067
     10               19
[2 rows x 2 columns]

  Month    nrow
      1   41979
     10    1999
[2 rows x 2 columns]

  sum_Cancelled
     0.0254175
     0.00950475
[2 rows x 1 column]

  Month    nrow    Cancellation_Rate
      1   41979           0.0254175
     10    1999           0.00950475
[2 rows x 3 columns]

In [18]:
# Generate a frequency table for the 'Cancelled' column
airlines_hex['Cancelled'].table()

# Because H2O can handle larger datasets, it is possible to generate tables that are larger than Python's capacity, so use caution when executing this command.

  Cancelled    Count
-----------  -------
          0    42892
          1     1086
[2 rows x 2 columns]

# Data Manipulation

In [19]:
from sklearn.datasets import load_iris
import pandas as pd

# Load iris dataset from sklearn and convert to pandas DataFrame
iris = load_iris()
iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
iris_df['target'] = iris.target

# Convert pandas DataFrame to h2o Frame
iris_hex = h2o.H2OFrame(iris_df, destination_frame = 'iris_hex')
# Ensure the target column is treated as a categorical factor
iris_hex['target'] = iris_hex['target'].asfactor()

# List all objects in h2o
h2o.ls()

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

/usr/local/lib/python3.10/dist-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install datatable (for Python 3.9 or lower), or polars and pyarrow (for Python 3.10 or above) and activate it using:

with h2o.utils.threading.local_context(polars_enabled=True, datatable_enabled=True):
    pandas_df = h2o_df.as_data_frame()

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"

               key
0     airlines_hex
1         iris_hex
2   py_10_sid_a081
3   py_12_sid_a081
4   py_14_sid_a081
5   py_16_sid_a081
6   py_17_sid_a081
7   py_18_sid_a081
8   py_19_sid_a081
9    py_1_sid_a081
10   py_2_sid_a081
11   py_3_sid_a081
12   py_4_sid_a081
13   py_5_sid_a081

In [20]:
# Splitting Frames
# h2o.splitFrame() does not give an exact split. H2O is designed
# to be efficient on big data using a probabilistic splitting method rather than an
# exact split. On small datasets, the sizes of the resulting splits will deviate from
# the expected value more than on big data, where they will be very close to
# exact.
iris_split = iris_hex.split_frame(ratios=[0.75], seed = 1234)

# Creates training set from 1st data set in split
iris_train = iris_split[0]

# Creates testing set from 2nd data set in split
iris_test = iris_split[1]

# List all objects in h2o
h2o.ls()

/usr/local/lib/python3.10/dist-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install datatable (for Python 3.9 or lower), or polars and pyarrow (for Python 3.10 or above) and activate it using:

with h2o.utils.threading.local_context(polars_enabled=True, datatable_enabled=True):
    pandas_df = h2o_df.as_data_frame()

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"

               key
0     airlines_hex
1         iris_hex
2   py_10_sid_a081
3   py_12_sid_a081
4   py_14_sid_a081
5   py_16_sid_a081
6   py_17_sid_a081
7   py_18_sid_a081
8   py_19_sid_a081
9    py_1_sid_a081
10  py_21_sid_a081
11  py_23_sid_a081
12  py_24_sid_a081
13   py_2_sid_a081
14   py_3_sid_a081
15   py_4_sid_a081
16   py_5_sid_a081

In [21]:
# Define the function
def simple_fun(x):
    return 2 * x + 5

# Apply the function to the 'Sepal.Length' column
calculated = simple_fun(iris_hex['sepal length (cm)'])

# Combine the original 'Sepal.Length' column with the calculated values
combined = iris_hex['sepal length (cm)'].cbind(calculated)

# Display the combined result
h2o.as_list(combined)

/usr/local/lib/python3.10/dist-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install datatable (for Python 3.9 or lower), or polars and pyarrow (for Python 3.10 or above) and activate it using:

with h2o.utils.threading.local_context(polars_enabled=True, datatable_enabled=True):
    pandas_df = h2o_df.as_data_frame()

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"

     sepal length (cm)  sepal length (cm)0
0                  5.1                15.2
1                  4.9                14.8
2                  4.7                14.4
3                  4.6                14.2
4                  5.0                15.0
..                 ...                 ...
145                6.7                18.4
146                6.3                17.6
147                6.5                18.0
148                6.2                17.4
149                5.9                16.8

[150 rows x 2 columns]

# Running Models

## Classification (1)

In [22]:
from h2o.estimators import H2OGradientBoostingEstimator

In [ ]:
# Train a GBM model
iris_gbm = H2OGradientBoostingEstimator()
iris_gbm.train(y = 'target',
               x = iris_df.columns[:-1].tolist(),
               training_frame = iris_train)

In [24]:
# Predict on the test set
predictions = iris_gbm.predict(iris_test)
print(predictions)

gbm prediction progress: |███████████████████████████████████████████████████████| (done) 100%
  predict        p0           p1           p2
        0  0.99861   0.000700155  0.000690257
        0  0.99861   0.000700194  0.0006903
        0  0.991104  0.0084341    0.00046142
        0  0.998743  0.000772911  0.00048404
        0  0.997291  0.0023294    0.000379907
        0  0.998743  0.000772674  0.000483892
        0  0.99774   0.00186488   0.000395214
        0  0.998743  0.000772674  0.000483892
        0  0.998397  0.00115858   0.000444536
        0  0.998635  0.000729049  0.00063585
[33 rows x 4 columns]

In [25]:
# Generate the performance metrics for the test set
performance = iris_gbm.model_performance(iris_test)

In [26]:
performance.confusion_matrix()

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class
0    1    2    Error      Rate
---  ---  ---  ---------  ------
15   0    0    0          0 / 15
0    11   1    0.0833333  1 / 12
0    1    5    0.166667   1 / 6
15   12   6    0.0606061  2 / 33

In [29]:
performance.hit_ratio_table()

Top-3 Hit Ratios:
k    hit_ratio
---  -----------
1    0.939394
2    1
3    1

## Classification (2)

In [30]:
from h2o.estimators import H2OGeneralizedLinearEstimator

# Import the prostate dataset
prostate_hex = h2o.import_file('https://raw.github.com/h2oai/h2o/master/smalldata/logreg/prostate.csv',
                               destination_frame='prostate_hex')

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

In [ ]:
# Train a GLM model for logistic classification
prostate_glm = H2OGeneralizedLinearEstimator(family = 'binomial', nfolds = 10)
prostate_glm.train(y='CAPSULE', x=['AGE', 'RACE', 'PSA', 'DCAPS'], training_frame = prostate_hex)

glm Model Build progress: |

/Users/mikolaj.mlodzikowski/.pyenv/versions/3.14.0/lib/python3.14/site-packages/h2o/estimators/estimator_base.py:192: RuntimeWarning: We have detected that your response column has only 2 unique values (0/1). If you wish to train a binary model instead of a regression model, convert your target column to categorical before training.
  warnings.warn(mesg["message"], RuntimeWarning)

██████████████████████████████████████████████████████| (done) 100%

Model Details
=============
H2OGeneralizedLinearEstimator : Generalized Linear Modeling
Model Key: GLM_model_python_1772973862355_2


GLM Model: summary
    family    link    regularization                                 number_of_predictors_total    number_of_active_predictors    number_of_iterations    training_frame
--  --------  ------  ---------------------------------------------  ----------------------------  -----------------------------  ----------------------  ----------------
    binomial  logit   Elastic Net (alpha = 0.5, lambda = 3.247E-4 )  4                             4                              4                       prostate_hex

ModelMetricsBinomialGLM: glm
** Reported on train data. **

MSE: 0.20270358163068206
RMSE: 0.45022614498791835
LogLoss: 0.5914634303487469
AUC: 0.7176009904696092
AUCPR: 0.6685393771546175
Gini: 0.43520198093921847
Null degrees of freedom: 379
Residual degrees of freedom: 375
Null deviance: 512.2888401848891
Residual deviance: 449.5122070650477
AIC: 459.5122070650477

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.28404756024881217
       0    1    Error    Rate
-----  ---  ---  -------  -------------
0      80   147  0.6476   (147.0/227.0)
1      18   135  0.1176   (18.0/153.0)
Total  98   282  0.4342   (165.0/380.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.284048     0.62069   274
max f2                       0.207093     0.77823   360
max f0point5                 0.413268     0.636672  108
max accuracy                 0.413268     0.705263  108
max precision                0.998478     1         0
max recall                   0.207093     1         360
max specificity              0.998478     1         0
max absolute_mcc             0.413268     0.369123  108
max min_per_class_accuracy   0.331806     0.647577  176
max mean_per_class_accuracy  0.373175     0.672123  126
max tns                      0.998478     227       0
max fns                      0.998478     152       0
max fps                      0.147756     227       369
max tps                      0.207093     153       360
max tnr                      0.998478     1         0
max fnr                      0.998478     0.993464  0
max fpr                      0.147756     1         369
max tpr                      0.207093     1         360

Gains/Lift Table: Avg response rate: 40.26 %, avg score: 40.26 %
group    cumulative_data_fraction    lower_threshold    lift      cumulative_lift    response_rate    score     cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  --------  -----------------  ---------------  --------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.0105263                   0.987059           2.48366   2.48366            1                0.995204  1                           0.995204            0.0261438       0.0261438                  148.366   148.366            0.0261438
2        0.0210526                   0.95534            2.48366   2.48366            1                0.973627  1                           0.984415            0.0261438       0.0522876                  148.366   148.366            0.0522876
3        0.0315789                   0.935194           1.86275   2.27669            0.75             0.943894  0.916667                    0.970908            0.0196078       0.0718954                  86.2745   127.669            0.0674901
4        0.0421053                   0.912739           1.86275   2.1732             0.75             0.921974  0.875                       0.958675            0.0196078       0.0915033                  86.2745   117.32             0.0826927
5        0.05                        0.88187            2.48366   2.22222            1                0.896478  0.894737                    0.948854            0.0196078       0.111111                   148.366   122.222            0.102301
6        0.1                         0.731384           1.83007   2.02614            0.736842         0.797248  0.815789                    0.873051            0.0915033       0.202614                   83.0065   102.614            0.171777
7        0.15                        0.602904           1.96078   2.00436            0.789474         0.664479  0.807018                    0.803527            0.0980392       0.300654                   96.0784   100.436            0.252195
8        0.2                         0.494151           1.30719   1.83007            0.526316         0.565456  0.736842                    0.744009            0.0653595       0.366013                   30.719    83.0065            0.277907
9        0.3                         0.399507           1.30719   1.65577            0.526316         0.446501  0.666667                    0.64484             0.130719        0.496732                   30.719    65.5773            0.329331
10       0.4                         0.350423           0.784314  1.43791            0.315789         0.369024  0.578947                    0.575886            0.0784314       0.575163                   -21.5686  43.7908            0.293225
11       0.5                         0.325118           1.04575   1.35948            0.421053         0.337642  0.547368                    0.528237            0.104575        0.679739                   4.57516   35.9477            0.300884
12       0.602632                    0.307252           0.764203  1.2581             0.307692         0.316306  0.50655                     0.492144            0.0784314       0.75817                    -23.5797  25.8099            0.260373
13       0.7                         0.290201           0.604134  1.16713            0.243243         0.297931  0.469925                    0.465129            0.0588235       0.816993                   -39.5866  16.7134            0.195848
14       0.8                         0.273379           0.915033  1.13562            0.368421         0.281465  0.457237                    0.442171            0.0915033       0.908497                   -8.49673  13.5621            0.181624
15       0.9                         0.254814           0.588235  1.0748             0.236842         0.264314  0.432749                    0.422409            0.0588235       0.96732                    -41.1765  7.48003            0.112695
16       1                           0.147756           0.326797  1                  0.131579         0.224628  0.402632                    0.402631            0.0326797       1                          -67.3203  0                  0

ModelMetricsBinomialGLM: glm
** Reported on cross-validation data. **

MSE: 0.20890245479926028
RMSE: 0.45705848072129707
LogLoss: 0.6078109884404936
AUC: 0.6887938729089287
AUCPR: 0.6405615332126248
Gini: 0.37758774581785737
Null degrees of freedom: 379
Residual degrees of freedom: 375
Null deviance: 514.2444521824076
Residual deviance: 461.93635121477524
AIC: 471.93635121477524

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.25731843681958866
       0    1    Error    Rate
-----  ---  ---  -------  -------------
0      43   184  0.8106   (184.0/227.0)
1      9    144  0.0588   (9.0/153.0)
Total  52   328  0.5079   (193.0/380.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.257318     0.598753  326
max f2                       0.240896     0.777549  357
max f0point5                 0.405681     0.619694  108
max accuracy                 0.405681     0.694737  108
max precision                0.997674     1         0
max recall                   0.145547     1         376
max specificity              0.997674     1         0
max absolute_mcc             0.405681     0.345395  108
max min_per_class_accuracy   0.333333     0.633987  179
max mean_per_class_accuracy  0.405681     0.659267  108
max tns                      0.997674     227       0
max fns                      0.997674     152       0
max fps                      0.131398     227       378
max tps                      0.145547     153       376
max tnr                      0.997674     1         0
max fnr                      0.997674     0.993464  0
max fpr                      0.131398     1         378
max tpr                      0.145547     1         376

Gains/Lift Table: Avg response rate: 40.26 %, avg score: 40.20 %
group    cumulative_data_fraction    lower_threshold    lift      cumulative_lift    response_rate    score     cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  --------  -----------------  ---------------  --------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.0105263                   0.986251           2.48366   2.48366            1                0.994646  1                           0.994646            0.0261438       0.0261438                  148.366   148.366            0.0261438
2        0.0210526                   0.958974           1.86275   2.1732             0.75             0.973049  0.875                       0.983847            0.0196078       0.0457516                  86.2745   117.32             0.0413463
3        0.0315789                   0.939652           1.86275   2.06972            0.75             0.947232  0.833333                    0.971642            0.0196078       0.0653595                  86.2745   106.972            0.0565489
4        0.0421053                   0.909983           2.48366   2.1732             1                0.928105  0.875                       0.960758            0.0261438       0.0915033                  148.366   117.32             0.0826927
5        0.05                        0.876369           2.48366   2.22222            1                0.885783  0.894737                    0.94892             0.0196078       0.111111                   148.366   122.222            0.102301
6        0.1                         0.734885           1.83007   2.02614            0.736842         0.801524  0.815789                    0.875222            0.0915033       0.202614                   83.0065   102.614            0.171777
7        0.15                        0.601456           1.69935   1.91721            0.684211         0.671759  0.77193                     0.807401            0.0849673       0.287582                   69.9346   91.7211            0.230313
8        0.2                         0.498819           1.30719   1.76471            0.526316         0.559804  0.710526                    0.745502            0.0653595       0.352941                   30.719    76.4706            0.256025
9        0.3                         0.398982           1.30719   1.6122             0.526316         0.442873  0.649123                    0.644625            0.130719        0.48366                    30.719    61.22              0.307449
10       0.4                         0.355044           0.915033  1.43791            0.368421         0.37078   0.578947                    0.576164            0.0915033       0.575163                   -8.49673  43.7908            0.293225
11       0.5                         0.326454           0.718954  1.29412            0.289474         0.339805  0.521053                    0.528892            0.0718954       0.647059                   -28.1046  29.4118            0.246178
12       0.6                         0.303749           0.718954  1.19826            0.289474         0.315162  0.482456                    0.493271            0.0718954       0.718954                   -28.1046  19.8257            0.19913
13       0.7                         0.287617           0.784314  1.13912            0.315789         0.295463  0.458647                    0.465012            0.0784314       0.797386                   -21.5686  13.9122            0.163024
14       0.8                         0.272013           0.718954  1.0866             0.289474         0.280755  0.4375                      0.44198             0.0718954       0.869281                   -28.1046  8.66013            0.115977
15       0.9                         0.250878           0.784314  1.05301            0.315789         0.260428  0.423977                    0.421808            0.0784314       0.947712                   -21.5686  5.30138            0.079871
16       1                           0.131398           0.522876  1                  0.210526         0.223935  0.402632                    0.40202             0.0522876       1                          -47.7124  0                  0

Cross-Validation Metrics Summary:
                      mean         sd           cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid    cv_6_valid    cv_7_valid    cv_8_valid    cv_9_valid    cv_10_valid
--------------------  -----------  -----------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  -------------
accuracy              0.6890375    0.11502903   0.6938776     0.5405405     0.6585366     0.5           0.6666667     0.7619048     0.8611111     0.8125        0.76666665    0.62857145
aic                   56.193634    11.894335    78.75284      64.313644     67.235954     59.59567      46.427635     61.2782       45.22379      42.013256     46.912376     50.182983
auc                   0.697506     0.061737914  0.67833334    0.59375       0.6425        0.6811224     0.6875        0.7409091     0.7163636     0.8174603     0.74666667    0.67045456
err                   0.31096247   0.11502903   0.30612245    0.45945945    0.34146342    0.5           0.33333334    0.23809524    0.1388889     0.1875        0.23333333    0.37142858
err_count             12.0         5.0990195    15.0          17.0          14.0          21.0          12.0          10.0          5.0           6.0           7.0           13.0
f0point5              0.6453399    0.14778008   0.6686047     0.53571427    0.5769231     0.45454547    0.53571427    0.75          0.85714287    0.8333333     0.75949365    0.48192772
f1                    0.6727204    0.08368531   0.75409836    0.63829786    0.6315789     0.5714286     0.6           0.75          0.7058824     0.75          0.7741935     0.55172414
f2                    0.7269312    0.07946935   0.86466163    0.7894737     0.6976744     0.7692308     0.6818182     0.75          0.6           0.6818182     0.7894737     0.6451613
lift_top_group        2.3444426    0.9568407    2.0416667     0.0           2.5625        3.0           3.0           2.1           3.2727273     2.2857144     2.0           3.1818182
loglikelihood         0.0          0.0          0.0           0.0           0.0           0.0           0.0           0.0           0.0           0.0           0.0           0.0
---                   ---          ---          ---           ---           ---           ---           ---           ---           ---           ---           ---           ---
mean_per_class_error  0.29758242   0.06928633   0.30083334    0.4122024     0.325         0.375         0.3125        0.23863636    0.22727273    0.20634921    0.23333333    0.34469697
mse                   0.20627183   0.036317043  0.25445744    0.25635156    0.24019799    0.20140208    0.16517648    0.21278843    0.15817359    0.16471393    0.21140885    0.1980479
null_deviance         51.424446    8.462586     69.92322      50.781864     54.879234     54.545513     46.722076     59.309452     46.084618     44.051655     42.96079      44.986027
pr_auc                0.6553465    0.10665805   0.64671415    0.5062832     0.52690685    0.57712       0.6733162     0.7226851     0.71938163    0.8315987     0.7661047     0.58335453
precision             0.6395392    0.20289372   0.6216216     0.48387095    0.54545456    0.4           0.5           0.75          1.0           0.9           0.75          0.44444445
r2                    0.124579184  0.12824175   -0.018253904  -0.044480048  -0.009432012  0.09369061    0.2567058     0.14691184    0.25457102    0.33068624    0.15436457    0.08102772
recall                0.78614175   0.1431129    0.9583333     0.9375        0.75          1.0           0.75          0.75          0.54545456    0.64285713    0.8           0.72727275
residual_deviance     46.193634    11.894335    68.75284      54.31364      57.23596      49.59567      36.427635     51.2782       35.22379      32.013256     36.912376     40.182983
rmse                  0.45257148   0.040150683  0.50443774    0.5063117     0.49009997    0.44877845    0.4064191     0.46128997    0.39771044    0.40584964    0.4597922     0.44502574
specificity           0.61869335   0.2587873    0.44          0.23809524    0.6           0.25          0.625         0.77272725    1.0           0.9444444     0.73333335    0.5833333
[24 rows x 13 columns]


Scoring History:
    timestamp            duration    iterations    negative_log_likelihood    objective    training_rmse    training_logloss    training_r2    training_auc    training_pr_auc    training_lift    training_classification_error
--  -------------------  ----------  ------------  -------------------------  -----------  ---------------  ------------------  -------------  --------------  -----------------  ---------------  -------------------------------
    2026-03-08 14:30:12  0.000 sec   0             256.144                    0.674064
    2026-03-08 14:30:12  0.000 sec   1             227.011                    0.597623
    2026-03-08 14:30:12  0.001 sec   2             224.855                    0.592045
    2026-03-08 14:30:12  0.001 sec   3             224.757                    0.591814
    2026-03-08 14:30:12  0.001 sec   4             224.756                    0.591813     0.450226         0.591463            0.157226       0.717601        0.668539           2.48366          0.434211

Variable Importances:
variable    relative_importance    scaled_importance    percentage
----------  ---------------------  -------------------  ------------
PSA         0.937727               1                    0.582369
DCAPS       0.408386               0.435506             0.253625
RACE        0.192433               0.205212             0.119509
AGE         0.0716479              0.0764059            0.0444965

[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.

In [ ]:
# Get cross-validation metrics
prostate_glm.cross_validation_metrics_summary().as_data_frame()

,,mean,sd,cv_1_valid,cv_2_valid,cv_3_valid,cv_4_valid,cv_5_valid,cv_6_valid,cv_7_valid,cv_8_valid,cv_9_valid,cv_10_valid
0,accuracy,0.689037,0.115029,0.693878,0.540540,0.658537,0.500000,0.666667,0.761905,0.861111,0.812500,0.766667,0.628571
1,aic,56.193634,11.894335,78.752840,64.313644,67.235954,59.595670,46.427635,61.278200,45.223790,42.013256,46.912376,50.182983
2,auc,0.697506,0.061738,0.678333,0.593750,0.642500,0.681122,0.687500,0.740909,0.716364,0.817460,0.746667,0.670455
3,err,0.310962,0.115029,0.306122,0.459459,0.341463,0.500000,0.333333,0.238095,0.138889,0.187500,0.233333,0.371429
4,err_count,12.000000,5.099019,15.000000,17.000000,14.000000,21.000000,12.000000,10.000000,5.000000,6.000000,7.000000,13.000000
5,f0point5,0.645340,0.147780,0.668605,0.535714,0.576923,0.454545,0.535714,0.750000,0.857143,0.833333,0.759494,0.481928
6,f1,0.672720,0.083685,0.754098,0.638298,0.631579,0.571429,0.600000,0.750000,0.705882,0.750000,0.774193,0.551724
7,f2,0.726931,0.079469,0.864662,0.789474,0.697674,0.769231,0.681818,0.750000,0.600000,0.681818,0.789474,0.645161
8,lift_top_group,2.344443,0.956841,2.041667,0.000000,2.562500,3.000000,3.000000,2.100000,3.272727,2.285714,2.000000,3.181818
9,loglikelihood,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,logloss,0.601902,0.088200,0.701560,0.733968,0.697999,0.590425,0.505939,0.610455,0.489219,0.500207,0.615206,0.574043
11,max_per_class_error,0.459193,0.179515,0.560000,0.761905,0.400000,0.750000,0.375000,0.250000,0.454545,0.357143,0.266667,0.416667
12,mcc,0.435974,0.150348,0.463053,0.236008,0.342381,0.316228,0.353553,0.522727,0.674200,0.628565,0.534523,0.288504
13,mean_per_class_accuracy,0.702418,0.069286,0.699167,0.587798,0.675000,0.625000,0.687500,0.761364,0.772727,0.793651,0.766667,0.655303
14,mean_per_class_error,0.297582,0.069286,0.300833,0.412202,0.325000,0.375000,0.312500,0.238636,0.227273,0.206349,0.233333,0.344697
15,mse,0.206272,0.036317,0.254457,0.256352,0.240198,0.201402,0.165176,0.212788,0.158174,0.164714,0.211409,0.198048
16,null_deviance,51.424446,8.462586,69.923220,50.781864,54.879234,54.545513,46.722076,59.309452,46.084618,44.051655,42.960790,44.986027
17,pr_auc,0.655347,0.106658,0.646714,0.506283,0.526907,0.577120,0.673316,0.722685,0.719382,0.831599,0.766105,0.583355
18,precision,0.639539,0.202894,0.621622,0.483871,0.545455,0.400000,0.500000,0.750000,1.000000,0.900000,0.750000,0.444444
19,r2,0.124579,0.128242,-0.018254,-0.044480,-0.009432,0.093691,0.256706,0.146912,0.254571,0.330686,0.154365,0.081028
20,recall,0.786142,0.143113,0.958333,0.937500,0.750000,1.000000,0.750000,0.750000,0.545455,0.642857,0.800000,0.727273
21,residual_deviance,46.193634,11.894335,68.752840,54.313640,57.235960,49.595670,36.427635,51.278200,35.223790,32.013256,36.912376,40.182983
22,rmse,0.452571,0.040151,0.504438,0.506312,0.490100,0.448778,0.406419,0.461290,0.397710,0.405850,0.459792,0.445026
23,specificity,0.618693,0.258787,0.440000,0.238095,0.600000,0.250000,0.625000,0.772727,1.000000,0.944444,0.733333,0.583333

In [ ]:
# Predict on the same dataset
prostate_glm.predict(prostate_hex)

glm prediction progress: |███████████████████████████████████████████████████████| (done) 100%

  predict         p0        p1
---------  ---------  --------
        0  0.744769   0.255231
        1  0.397624   0.602376
        1  0.412673   0.587327
        1  0.372769   0.627231
        1  0.646499   0.353501
        1  0.433663   0.566337
        1  0.265466   0.734534
        1  0.0614316  0.938568
        0  0.730583   0.269417
        1  0.467175   0.532825
[380 rows x 3 columns]

In [34]:
# Calculate AUC
auc = prostate_glm.auc()
print(f'AUC: {auc}')

AUC: 0.7176009904696092

In [ ]:
# Generate the confusion matrix
confusion_matrix = prostate_glm.confusion_matrix()
print(confusion_matrix)

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.28404756024881217
       0    1    Error    Rate
-----  ---  ---  -------  -------------
0      80   147  0.6476   (147.0/227.0)
1      18   135  0.1176   (18.0/153.0)
Total  98   282  0.4342   (165.0/380.0)

In [ ]:
# Get performance metrics on the training data
performance = prostate_glm.model_performance(prostate_hex)
print(performance)

ModelMetricsBinomialGLM: glm
** Reported on test data. **

MSE: 0.20270358163068206
RMSE: 0.45022614498791835
LogLoss: 0.5914634303487469
AUC: 0.7176009904696092
AUCPR: 0.6685393771546175
Gini: 0.43520198093921847
Null degrees of freedom: 379
Residual degrees of freedom: 375
Null deviance: 512.2888401848891
Residual deviance: 449.5122070650477
AIC: 459.5122070650477

Confusion Matrix (Act/Pred) for max f1 @ threshold = 0.28404756024881217
       0    1    Error    Rate
-----  ---  ---  -------  -------------
0      80   147  0.6476   (147.0/227.0)
1      18   135  0.1176   (18.0/153.0)
Total  98   282  0.4342   (165.0/380.0)

Maximum Metrics: Maximum metrics at their respective thresholds
metric                       threshold    value     idx
---------------------------  -----------  --------  -----
max f1                       0.284048     0.62069   274
max f2                       0.207093     0.77823   360
max f0point5                 0.413268     0.636672  108
max accuracy                 0.413268     0.705263  108
max precision                0.998478     1         0
max recall                   0.207093     1         360
max specificity              0.998478     1         0
max absolute_mcc             0.413268     0.369123  108
max min_per_class_accuracy   0.331806     0.647577  176
max mean_per_class_accuracy  0.373175     0.672123  126
max tns                      0.998478     227       0
max fns                      0.998478     152       0
max fps                      0.147756     227       369
max tps                      0.207093     153       360
max tnr                      0.998478     1         0
max fnr                      0.998478     0.993464  0
max fpr                      0.147756     1         369
max tpr                      0.207093     1         360

Gains/Lift Table: Avg response rate: 40.26 %, avg score: 40.26 %
group    cumulative_data_fraction    lower_threshold    lift      cumulative_lift    response_rate    score     cumulative_response_rate    cumulative_score    capture_rate    cumulative_capture_rate    gain      cumulative_gain    kolmogorov_smirnov
-------  --------------------------  -----------------  --------  -----------------  ---------------  --------  --------------------------  ------------------  --------------  -------------------------  --------  -----------------  --------------------
1        0.0105263                   0.987059           2.48366   2.48366            1                0.995204  1                           0.995204            0.0261438       0.0261438                  148.366   148.366            0.0261438
2        0.0210526                   0.95534            2.48366   2.48366            1                0.973627  1                           0.984415            0.0261438       0.0522876                  148.366   148.366            0.0522876
3        0.0315789                   0.935194           1.86275   2.27669            0.75             0.943894  0.916667                    0.970908            0.0196078       0.0718954                  86.2745   127.669            0.0674901
4        0.0421053                   0.912739           1.86275   2.1732             0.75             0.921974  0.875                       0.958675            0.0196078       0.0915033                  86.2745   117.32             0.0826927
5        0.05                        0.88187            2.48366   2.22222            1                0.896478  0.894737                    0.948854            0.0196078       0.111111                   148.366   122.222            0.102301
6        0.1                         0.731384           1.83007   2.02614            0.736842         0.797248  0.815789                    0.873051            0.0915033       0.202614                   83.0065   102.614            0.171777
7        0.15                        0.602904           1.96078   2.00436            0.789474         0.664479  0.807018                    0.803527            0.0980392       0.300654                   96.0784   100.436            0.252195
8        0.2                         0.494151           1.30719   1.83007            0.526316         0.565456  0.736842                    0.744009            0.0653595       0.366013                   30.719    83.0065            0.277907
9        0.3                         0.399507           1.30719   1.65577            0.526316         0.446501  0.666667                    0.64484             0.130719        0.496732                   30.719    65.5773            0.329331
10       0.4                         0.350423           0.784314  1.43791            0.315789         0.369024  0.578947                    0.575886            0.0784314       0.575163                   -21.5686  43.7908            0.293225
11       0.5                         0.325118           1.04575   1.35948            0.421053         0.337642  0.547368                    0.528237            0.104575        0.679739                   4.57516   35.9477            0.300884
12       0.602632                    0.307252           0.764203  1.2581             0.307692         0.316306  0.50655                     0.492144            0.0784314       0.75817                    -23.5797  25.8099            0.260373
13       0.7                         0.290201           0.604134  1.16713            0.243243         0.297931  0.469925                    0.465129            0.0588235       0.816993                   -39.5866  16.7134            0.195848
14       0.8                         0.273379           0.915033  1.13562            0.368421         0.281465  0.457237                    0.442171            0.0915033       0.908497                   -8.49673  13.5621            0.181624
15       0.9                         0.254814           0.588235  1.0748             0.236842         0.264314  0.432749                    0.422409            0.0588235       0.96732                    -41.1765  7.48003            0.112695
16       1                           0.147756           0.326797  1                  0.131579         0.224628  0.402632                    0.402631            0.0326797       1                          -67.3203  0                  0

## Regression

The Loblolly data frame has 84 rows and 3 columns of records of the growth of Loblolly pine trees.

Kung, F. H. (1986), Fitting logistic growth curve with predetermined carrying capacity, in Proceedings of the Statistical Computing Section, American Statistical Association, 340–343.

Pinheiro, J. C. and Bates, D. M. (2000) Mixed-effects Models in S and S-PLUS, Springer.

In [ ]:
# Import the Loblolly dataset from the CSV file
loblolly_hex = h2o.import_file('../data/loblolly.csv', destination_frame = 'Loblolly_hex')
loblolly_hex

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

  height    age    Seed
--------  -----  ------
    4.51      3     301
   10.89      5     301
   28.72     10     301
   41.74     15     301
   52.7      20     301
   60.92     25     301
    4.55      3     303
   10.92      5     303
   29.07     10     303
   42.83     15     303
[84 rows x 3 columns]

In [ ]:
# Train a GLM model for regression
loblolly_glm = H2OGeneralizedLinearEstimator(nfolds = 10)
loblolly_glm.train(y='height', x=['age'], training_frame = loblolly_hex)

glm Model Build progress: |██████████████████████████████████████████████████████| (done) 100%

Model Details
=============
H2OGeneralizedLinearEstimator : Generalized Linear Modeling
Model Key: GLM_model_python_1772973862355_36


GLM Model: summary
    family    link      regularization                                number_of_predictors_total    number_of_active_predictors    number_of_iterations    training_frame
--  --------  --------  --------------------------------------------  ----------------------------  -----------------------------  ----------------------  ----------------
    gaussian  identity  Elastic Net (alpha = 0.5, lambda = 0.04044 )  1                             1                              1                       Loblolly_hex

ModelMetricsRegressionGLM: glm
** Reported on train data. **

MSE: 8.65966603967151
RMSE: 2.9427310511957274
MAE: 2.5495490100060314
RMSLE: 0.20121262346129062
Mean Residual Deviance: 8.65966603967151
R^2: 0.9794945208642793
Null degrees of freedom: 83
Residual degrees of freedom: 82
Null deviance: 35474.02830813409
Residual deviance: 727.4119473324068
AIC: 425.7104708741088

ModelMetricsRegressionGLM: glm
** Reported on cross-validation data. **

MSE: 9.250559396420957
RMSE: 3.041473227963869
MAE: 2.649156709512426
RMSLE: 0.2123724994290228
Mean Residual Deviance: 9.250559396420957
R^2: 0.9780953270220741
Null degrees of freedom: 83
Residual degrees of freedom: 82
Null deviance: 36262.27845733087
Residual deviance: 777.0469892993603
AIC: 431.2551316770855

Cross-Validation Metrics Summary:
                        mean      sd         cv_1_valid    cv_2_valid    cv_3_valid    cv_4_valid    cv_5_valid    cv_6_valid    cv_7_valid    cv_8_valid    cv_9_valid    cv_10_valid
----------------------  --------  ---------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  ------------  -------------
aic                     47.8713   8.32095    46.5263       38.2677       37.2196       45.6066       55.8318       55.181        55.1358       42.7084       41.2894       60.9467
loglikelihood           0         0          0             0             0             0             0             0             0             0             0             0
mae                     2.62915   0.579055   2.74994       2.66796       2.04155       2.03515       2.71011       3.62829       2.46275       2.96708       1.76253       3.26615
mean_residual_deviance  9.2304    3.65804    9.2804        12.6805       5.06357       4.77242       8.54462       13.8278       7.97016       11.0915       4.82251       14.2505
mse                     9.2304    3.65804    9.2804        12.6805       5.06357       4.77242       8.54462       13.8278       7.97016       11.0915       4.82251       14.2505
null_deviance           3626.23   1770.95    4003.2        1025.35       1040.14       3644.43       6461.59       4717.15       4888.36       1911.67       4264.84       4305.56
r2                      0.969369  0.0195303  0.975193      0.925431      0.955989      0.988203      0.985115      0.973616      0.976613      0.957135      0.990661      0.96574
residual_deviance       77.7047   34.9399    74.2432       76.083        35.445        42.9518       85.4462       124.45        79.7016       77.6407       38.5801       142.505
rmse                    2.98084   0.61913    3.04638       3.56097       2.25024       2.18459       2.92312       3.71857       2.82315       3.33039       2.19602       3.77499
rmsle                   0.187776  0.0902929  0.299992      0.106922      0.162519      0.169589      0.340744      0.293346      0.129368      0.103337      0.0983951     0.17355

Scoring History:
    timestamp            duration    iterations    negative_log_likelihood    objective    training_rmse    training_deviance    training_mae    training_r2
--  -------------------  ----------  ------------  -------------------------  -----------  ---------------  -------------------  --------------  -------------
    2026-03-08 14:34:04  0.000 sec   0             35474                      422.31
    2026-03-08 14:34:04  0.001 sec   1                                                     2.94273          8.65967              2.54955         0.979495

Variable Importances:
variable    relative_importance    scaled_importance    percentage
----------  ---------------------  -------------------  ------------
age         20.0346                1                    1

[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.

In [ ]:
# Predict using the GLM model
glm_predict = loblolly_glm.predict(loblolly_hex)
print(glm_predict)

In [40]:
from h2o.automl import H2OAutoML

In [ ]:
# Train an AutoML model
loblolly_automl = H2OAutoML(max_runtime_secs = 60)
loblolly_automl.train(y='height', x=['age'], training_frame=loblolly_hex)

In [ ]:
loblolly_automl.get_leaderboard()

In [ ]:
# Get the leader model from AutoML
leader_model = loblolly_automl.leader
print(leader_model)

# Predict using the AutoML leader model
automl_predict = leader_model.predict(loblolly_hex)
print(automl_predict)

## Clustering

In [44]:
from h2o.estimators import H2OKMeansEstimator

In [ ]:
iris_kmeans = H2OKMeansEstimator(k = 3)
iris_kmeans.train(x = list(range(0, 4)),
                  training_frame = iris_hex)

In [ ]:
# Print model details
print(iris_kmeans)

In [ ]:
# Show cluster centers
print("Cluster Centers: ", iris_kmeans.centers())

In [ ]:
# Show clustering metrics
print("Clustering Metrics: ", iris_kmeans._model_json['output']['training_metrics'])

## PCA

In [49]:
from h2o.estimators import H2OPrincipalComponentAnalysisEstimator

In [ ]:
iris_pca_data = iris_hex[:, :-1]

# Train a PCA model
iris_pca = H2OPrincipalComponentAnalysisEstimator(k=2, transform='NORMALIZE')
iris_pca.train(training_frame=iris_pca_data)

In [ ]:
# Print model details
print(iris_pca)

In [ ]:
# Show the principal components
print("Principal Components: ", iris_pca._model_json['output']['importance'])

In [53]:
# Get the principal component projections
pca_projections = iris_pca.predict(iris_pca_data)
print(pca_projections)

pca prediction progress: |███████████████████████████████████████████████████████| (done) 100%
     PC1         PC2
0.630703   0.107578
0.622905  -0.10426
0.66952   -0.0514171
0.654153  -0.102885
0.648788   0.133488
0.535273   0.289616
0.656538   0.0107245
0.62578    0.0571335
0.675644  -0.200703
0.645645  -0.067208
[150 rows x 2 columns]

# Case Study (MNIST)

In [54]:
# URLs to the train and test datasets
train_file = 'https://h2o-public-test-data.s3.amazonaws.com/bigdata/laptop/mnist/train.csv.gz'
test_file = 'https://h2o-public-test-data.s3.amazonaws.com/bigdata/laptop/mnist/test.csv.gz'

# Import the datasets
train = h2o.import_file(train_file)
test = h2o.import_file(test_file)

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

/var/folders/bk/2s3xmq_d3kvghcpmt0hzcmx40000gp/T/ipykernel_17253/3853061380.py:10: H2ODeprecationWarning: ``summary()`` is deprecated, please use ``show_summary()`` or ``get_summary()`` instead
  train.summary()

         C1     C2     C3     C4     C5     C6     C7     C8     C9     C10    C11    C12    C13                 C14                   C15                    C16                   C17    C18    C19    C20    C21    C22    C23    C24    C25    C26    C27    C28    C29    C30    C31    C32    C33                    C34                    C35                   C36                   C37                  C38                C39                  C40                  C41                  C42                  C43                  C44                C45                  C46                C47                  C48                  C49                   C50                   C51                   C52                   C53    C54    C55    C56    C57    C58    C59                    C60                  C61                 C62                   C63                 C64                C65                 C66                 C67               C68                 C69                 C70                 C71                 C72                 C73                C74                 C75                 C76                C77                 C78                 C79                 C80                  C81                  C82                   C83    C84    C85    C86    C87                    C88                 C89                   C90                  C91                  C92                C93                 C94                 C95                 C96                 C97                C98                C99                 C100                C101                C102                C103               C104              C105                C106                C107                C108                C109                 C110                  C111              C112    C113    C114                   C115                  C116                C117                 C118                C119                C120                C121                C122               C123                C124               C125                C126               C127               C128              C129                C130                C131                C132                C133                C134               C135                C136                C137                C138                C139               C140                  C141    C142    C143                  C144               C145                C146               C147                C148               C149                C150                C151                C152               C153              C154                C155                C156                C157                C158                C159               C160               C161               C162                C163                C164                C165                C166                C167                 C168                C169    C170                   C171               C172                 C173                C174               C175               C176                C177               C178                C179                C180                C181                C182                C183                C184                C185                C186                C187                C188               C189                C190               C191               C192                C193                C194                C195                C196                C197                   C198                  C199                 C200                C201               C202               C203                C204                C205                C206               C207                C208                C209                C210                C211                C212                C213                C214                C215                C216                C217               C218                C219                C220               C221                C222                C223               C224                 C225                  C226                 C227                 C228               C229                C230               C231                C232                C233               C234                C235                C236                C237                C238                C239                C240                C241                C242                C243                C244                C245                C246               C247               C248                C249               C250                C251                C252                  C253                  C254                 C255                C256                C257                C258               C259                C260                C261               C262                C263                C264                C265              C266                C267                C268                C269                C270                C271                C272                C273                C274               C275                C276                C277                C278                C279                 C280                  C281                  C282                 C283                C284                C285               C286                C287                C288                C289               C290                C291              C292                C293                C294               C295                C296                C297                C298                C299                C300                C301               C302               C303                C304                C305                C306                C307                 C308                  C309                  C310               C311                 C312                C313                C314               C315                C316                C317               C318                C319                C320                C321                C322                C323               C324                C325                C326                C327                C328                C329               C330               C331               C332                C333                C334                C335               C336                  C337                C338                 C339                 C340                C341                C342               C343                C344                C345                C346                C347               C348                C349                C350                C351                C352                C353                C354                C355                C356               C357               C358                C359                C360               C361               C362               C363                 C364                  C365                   C366                C367                 C368                C369                C370                C371               C372               C373               C374               C375                C376                C377                C378                C379                C380                C381                C382                C383                C384                C385               C386               C387              C388                C389                C390               C391                 C392                  C393                   C394               C395                 C396                 C397                C398                C399                C400                C401               C402                C403               C404                C405                C406                C407                C408                C409                C410                C411                C412               C413                C414                C415                C416                C417               C418                C419                C420                   C421                   C422                   C423               C424                C425               C426              C427                C428                C429                C430                C431                C432               C433                C434                C435                C436               C437                C438                C439                C440                C441               C442                C443                C444               C445                C446                C447                 C448                  C449                   C450                  C451                 C452                C453                C454                C455               C456               C457                C458               C459                C460                C461                C462                C463                C464                C465                C466                C467                C468                C469               C470               C471                C472                C473               C474                C475               C476                C477    C478                   C479               C480                C481               C482                C483               C484               C485               C486                C487                C488                C489                C490                C491                C492               C493                C494                C495                C496                C497               C498                C499               C500               C501                C502                C503                 C504                  C505                   C506                  C507               C508               C509               C510                C511                C512                C513               C514               C515                C516                C517                C518                C519                C520                C521                C522                C523                C524                C525               C526                C527               C528                C529                C530                C531                 C532                  C533                    C534                  C535                 C536                C537               C538                C539               C540                C541                C542                C543                C544                C545                C546                C547                C548                C549                C550                C551                C552                C553                C554               C555               C556               C557                C558                C559               C560                  C561    C562                  C563               C564                C565               C566               C567               C568                C569               C570              C571                C572                C573                C574                C575                C576                C577                C578                C579               C580               C581               C582                C583                C584              C585                C586                C587                 C588                   C589                   C590                C591                 C592                C593                C594                C595               C596                C597                C598                C599                C600                C601                C602                C603                C604                C605               C606                C607               C608               C609                C610                C611                C612               C613                C614                C615               C616                 C617                   C618                   C619                 C620                C621                C622                C623                C624                C625               C626                C627                C628                C629                C630               C631                C632                C633               C634               C635               C636                C637                C638               C639                C640               C641                C642                 C643                  C644                C645    C646    C647                 C648                C649                C650               C651                C652                C653               C654               C655               C656                C657                C658                C659                C660                C661                C662              C663                C664                C665               C666                C667                C668                C669                C670                  C671                  C672    C673    C674    C675                C676               C677                C678               C679                C680               C681                C682                C683               C684               C685               C686               C687                C688               C689                C690                C691               C692                C693                C694                C695                C696                 C697                 C698                  C699                   C700    C701    C702    C703                   C704                  C705                 C706              C707                C708                C709               C710               C711                C712                C713                C714               C715                C716                C717               C718               C719               C720                C721                C722                C723                C724                 C725                  C726                   C727                   C728    C729    C730    C731    C732                   C733               C734                 C735                C736               C737                C738                C739                C740                C741                C742                C743                C744                C745                C746               C747                C748                C749                C750               C751                 C752                  C753                   C754                   C755    C756    C757    C758    C759    C760    C761                  C762                  C763                  C764                C765                 C766                 C767                C768                 C769                C770                C771                C772                C773                 C774                C775                 C776                 C777                 C778                  C779                  C780                 C781    C782    C783    C784    C785

         C1     C2     C3     C4     C5     C6     C7     C8     C9     C10    C11    C12    C13    C14    C15    C16    C17    C18    C19    C20    C21    C22    C23    C24    C25    C26    C27    C28    C29    C30    C31    C32    C33    C34     C35     C36     C37                 C38                 C39                 C40                C41                C42                C43                C44                C45                C46                 C47                C48                  C49                 C50    C51    C52    C53    C54    C55    C56    C57    C58    C59    C60    C61    C62                C63                C64                C65                C66                C67                 C68                 C69                 C70                 C71                C72                 C73                C74                 C75                C76                 C77                 C78                C79                C80                 C81     C82    C83    C84    C85    C86    C87    C88    C89                 C90                 C91                 C92                C93                 C94                 C95                C96                 C97                C98                C99                C100                C101               C102                C103               C104               C105               C106                C107                C108              C109                C110              C111    C112    C113    C114    C115    C116                  C117               C118               C119                C120               C121                C122               C123               C124               C125               C126               C127               C128               C129               C130               C131               C132                C133               C134               C135                C136               C137                C138               C139               C140    C141    C142                 C143                   C144               C145               C146                C147                C148                C149                C150               C151               C152               C153               C154                C155               C156                C157                C158                C159            C160               C161               C162                C163               C164               C165                C166                C167              C168    C169    C170    C171                 C172               C173               C174               C175                C176                C177                C178               C179               C180                C181                C182                C183                C184                C185                C186                C187                C188                C189               C190               C191               C192               C193               C194               C195               C196                C197    C198                C199               C200                C201                C202              C203               C204               C205               C206               C207                C208                C209                C210                C211                C212                C213                C214                C215                C216                C217                C218               C219               C220                C221                C222                C223               C224                C225    C226               C227               C228                C229               C230               C231               C232               C233               C234                C235                C236               C237                C238                C239                C240                C241                C242                C243                C244                C245                C246               C247               C248                C249                C250                C251                C252                 C253                C254               C255               C256               C257               C258                C259                C260               C261               C262                C263               C264                C265                C266                C267                C268                C269                C270                C271                C272                C273                C274               C275               C276                C277               C278                C279               C280                C281               C282               C283               C284              C285                C286               C287               C288               C289               C290                C291                C292                C293                C294                C295                C296                C297               C298                C299                C300                C301                C302               C303               C304               C305                C306                C307               C308                C309    C310               C311               C312                C313                C314                C315               C316               C317                C318                C319                C320                C321                C322               C323                C324                C325                C326                C327               C328                C329                C330               C331               C332               C333                C334                C335                 C336                C337    C338                C339               C340                C341                C342                C343               C344               C345                C346                C347                C348                C349                C350                C351                C352                C353                C354                C355                C356                C357               C358              C359               C360                C361                C362               C363                C364    C365    C366                  C367                C368              C369                C370                C371               C372               C373                C374                C375                C376                C377                C378                C379                C380                C381                C382                C383                C384                C385               C386              C387               C388                C389                C390                C391                C392    C393    C394    C395                C396               C397                C398               C399               C400               C401                C402                C403                C404                C405                C406                C407                C408                C409                C410                C411                C412                C413               C414               C415               C416               C417               C418                C419                C420    C421    C422    C423                 C424               C425               C426               C427               C428               C429                C430               C431                C432                C433                C434                C435                C436                C437                C438                C439                C440                C441               C442               C443               C444                C445                C446                C447               C448                C449    C450                  C451               C452             C453               C454                C455               C456               C457               C458                C459                C460                C461               C462               C463                C464                C465                C466                C467                C468                C469               C470               C471                C472               C473                C474                C475                C476                C477    C478    C479                C480                C481                C482               C483               C484               C485                C486                C487                C488               C489              C490                C491                C492               C493                C494                C495                C496                C497               C498               C499                C500                C501                C502                C503               C504                C505    C506                  C507               C508                C509               C510               C511               C512                C513               C514                C515                C516                C517                C518                C519                C520                C521                C522                C523                C524                C525              C526              C527               C528                C529              C530                C531               C532                C533    C534                  C535                 C536               C537               C538               C539              C540               C541               C542                C543                C544                C545                C546                C547                C548                C549                C550                C551                C552                C553               C554               C555               C556                C557               C558                C559                C560    C561    C562    C563               C564                C565               C566                C567              C568               C569                C570                C571                C572                C573              C574                C575               C576                C577                C578               C579                C580               C581               C582               C583               C584                C585               C586                C587               C588    C589    C590    C591               C592                C593                C594                C595               C596               C597                C598                C599                C600                C601                C602                C603               C604                C605                C606                C607                C608               C609               C610               C611                C612                C613                C614               C615               C616    C617    C618    C619               C620                C621                C622               C623                C624              C625               C626                C627                C628                C629                C630                C631                C632                C633                C634                C635               C636               C637                C638                C639               C640                C641                C642               C643                C644    C645    C646                 C647                C648               C649               C650                C651               C652                C653               C654              C655                C656               C657                C658                C659                C660                C661               C662                C663                C664               C665               C666               C667               C668                C669               C670                C671    C672    C673    C674    C675    C676                C677               C678                C679                C680              C681                C682               C683               C684               C685               C686               C687               C688               C689              C690                C691                C692              C693               C694                C695               C696               C697               C698    C699    C700    C701    C702    C703    C704                 C705                C706               C707               C708               C709               C710             C711               C712               C713               C714               C715               C716                C717               C718                C719               C720                C721               C722                C723               C724                C725                  C726                C727    C728    C729    C730    C731    C732    C733                 C734              C735              C736                C737                C738               C739                C740               C741               C742               C743               C744               C745                C746                C747               C748                C749                C750               C751               C752                C753                   C754    C755    C756    C757    C758    C759    C760    C761    C762    C763                 C764               C765              C766               C767               C768               C769               C770               C771                C772                C773               C774               C775                C776               C777                C778                   C779    C780    C781    C782    C783    C784    C785

In [ ]:

# Display a brief summary of the data
train.show_summary()
test.show_summary()

         C1     C2     C3     C4     C5     C6     C7     C8     C9     C10    C11    C12    C13                 C14                   C15                    C16                   C17    C18    C19    C20    C21    C22    C23    C24    C25    C26    C27    C28    C29    C30    C31    C32    C33                    C34                    C35                   C36                   C37                  C38                C39                  C40                  C41                  C42                  C43                  C44                C45                  C46                C47                  C48                  C49                   C50                   C51                   C52                   C53    C54    C55    C56    C57    C58    C59                    C60                  C61                 C62                   C63                 C64                C65                 C66                 C67               C68                 C69                 C70                 C71                 C72                 C73                C74                 C75                 C76                C77                 C78                 C79                 C80                  C81                  C82                   C83    C84    C85    C86    C87                    C88                 C89                   C90                  C91                  C92                C93                 C94                 C95                 C96                 C97                C98                C99                 C100                C101                C102                C103               C104              C105                C106                C107                C108                C109                 C110                  C111              C112    C113    C114                   C115                  C116                C117                 C118                C119                C120                C121                C122               C123                C124               C125                C126               C127               C128              C129                C130                C131                C132                C133                C134               C135                C136                C137                C138                C139               C140                  C141    C142    C143                  C144               C145                C146               C147                C148               C149                C150                C151                C152               C153              C154                C155                C156                C157                C158                C159               C160               C161               C162                C163                C164                C165                C166                C167                 C168                C169    C170                   C171               C172                 C173                C174               C175               C176                C177               C178                C179                C180                C181                C182                C183                C184                C185                C186                C187                C188               C189                C190               C191               C192                C193                C194                C195                C196                C197                   C198                  C199                 C200                C201               C202               C203                C204                C205                C206               C207                C208                C209                C210                C211                C212                C213                C214                C215                C216                C217               C218                C219                C220               C221                C222                C223               C224                 C225                  C226                 C227                 C228               C229                C230               C231                C232                C233               C234                C235                C236                C237                C238                C239                C240                C241                C242                C243                C244                C245                C246               C247               C248                C249               C250                C251                C252                  C253                  C254                 C255                C256                C257                C258               C259                C260                C261               C262                C263                C264                C265              C266                C267                C268                C269                C270                C271                C272                C273                C274               C275                C276                C277                C278                C279                 C280                  C281                  C282                 C283                C284                C285               C286                C287                C288                C289               C290                C291              C292                C293                C294               C295                C296                C297                C298                C299                C300                C301               C302               C303                C304                C305                C306                C307                 C308                  C309                  C310               C311                 C312                C313                C314               C315                C316                C317               C318                C319                C320                C321                C322                C323               C324                C325                C326                C327                C328                C329               C330               C331               C332                C333                C334                C335               C336                  C337                C338                 C339                 C340                C341                C342               C343                C344                C345                C346                C347               C348                C349                C350                C351                C352                C353                C354                C355                C356               C357               C358                C359                C360               C361               C362               C363                 C364                  C365                   C366                C367                 C368                C369                C370                C371               C372               C373               C374               C375                C376                C377                C378                C379                C380                C381                C382                C383                C384                C385               C386               C387              C388                C389                C390               C391                 C392                  C393                   C394               C395                 C396                 C397                C398                C399                C400                C401               C402                C403               C404                C405                C406                C407                C408                C409                C410                C411                C412               C413                C414                C415                C416                C417               C418                C419                C420                   C421                   C422                   C423               C424                C425               C426              C427                C428                C429                C430                C431                C432               C433                C434                C435                C436               C437                C438                C439                C440                C441               C442                C443                C444               C445                C446                C447                 C448                  C449                   C450                  C451                 C452                C453                C454                C455               C456               C457                C458               C459                C460                C461                C462                C463                C464                C465                C466                C467                C468                C469               C470               C471                C472                C473               C474                C475               C476                C477    C478                   C479               C480                C481               C482                C483               C484               C485               C486                C487                C488                C489                C490                C491                C492               C493                C494                C495                C496                C497               C498                C499               C500               C501                C502                C503                 C504                  C505                   C506                  C507               C508               C509               C510                C511                C512                C513               C514               C515                C516                C517                C518                C519                C520                C521                C522                C523                C524                C525               C526                C527               C528                C529                C530                C531                 C532                  C533                    C534                  C535                 C536                C537               C538                C539               C540                C541                C542                C543                C544                C545                C546                C547                C548                C549                C550                C551                C552                C553                C554               C555               C556               C557                C558                C559               C560                  C561    C562                  C563               C564                C565               C566               C567               C568                C569               C570              C571                C572                C573                C574                C575                C576                C577                C578                C579               C580               C581               C582                C583                C584              C585                C586                C587                 C588                   C589                   C590                C591                 C592                C593                C594                C595               C596                C597                C598                C599                C600                C601                C602                C603                C604                C605               C606                C607               C608               C609                C610                C611                C612               C613                C614                C615               C616                 C617                   C618                   C619                 C620                C621                C622                C623                C624                C625               C626                C627                C628                C629                C630               C631                C632                C633               C634               C635               C636                C637                C638               C639                C640               C641                C642                 C643                  C644                C645    C646    C647                 C648                C649                C650               C651                C652                C653               C654               C655               C656                C657                C658                C659                C660                C661                C662              C663                C664                C665               C666                C667                C668                C669                C670                  C671                  C672    C673    C674    C675                C676               C677                C678               C679                C680               C681                C682                C683               C684               C685               C686               C687                C688               C689                C690                C691               C692                C693                C694                C695                C696                 C697                 C698                  C699                   C700    C701    C702    C703                   C704                  C705                 C706              C707                C708                C709               C710               C711                C712                C713                C714               C715                C716                C717               C718               C719               C720                C721                C722                C723                C724                 C725                  C726                   C727                   C728    C729    C730    C731    C732                   C733               C734                 C735                C736               C737                C738                C739                C740                C741                C742                C743                C744                C745                C746               C747                C748                C749                C750               C751                 C752                  C753                   C754                   C755    C756    C757    C758    C759    C760    C761                  C762                  C763                  C764                C765                 C766                 C767                C768                 C769                C770                C771                C772                C773                 C774                C775                 C776                 C777                 C778                  C779                  C780                 C781    C782    C783    C784    C785

         C1     C2     C3     C4     C5     C6     C7     C8     C9     C10    C11    C12    C13    C14    C15    C16    C17    C18    C19    C20    C21    C22    C23    C24    C25    C26    C27    C28    C29    C30    C31    C32    C33    C34     C35     C36     C37                 C38                 C39                 C40                C41                C42                C43                C44                C45                C46                 C47                C48                  C49                 C50    C51    C52    C53    C54    C55    C56    C57    C58    C59    C60    C61    C62                C63                C64                C65                C66                C67                 C68                 C69                 C70                 C71                C72                 C73                C74                 C75                C76                 C77                 C78                C79                C80                 C81     C82    C83    C84    C85    C86    C87    C88    C89                 C90                 C91                 C92                C93                 C94                 C95                C96                 C97                C98                C99                C100                C101               C102                C103               C104               C105               C106                C107                C108              C109                C110              C111    C112    C113    C114    C115    C116                  C117               C118               C119                C120               C121                C122               C123               C124               C125               C126               C127               C128               C129               C130               C131               C132                C133               C134               C135                C136               C137                C138               C139               C140    C141    C142                 C143                   C144               C145               C146                C147                C148                C149                C150               C151               C152               C153               C154                C155               C156                C157                C158                C159            C160               C161               C162                C163               C164               C165                C166                C167              C168    C169    C170    C171                 C172               C173               C174               C175                C176                C177                C178               C179               C180                C181                C182                C183                C184                C185                C186                C187                C188                C189               C190               C191               C192               C193               C194               C195               C196                C197    C198                C199               C200                C201                C202              C203               C204               C205               C206               C207                C208                C209                C210                C211                C212                C213                C214                C215                C216                C217                C218               C219               C220                C221                C222                C223               C224                C225    C226               C227               C228                C229               C230               C231               C232               C233               C234                C235                C236               C237                C238                C239                C240                C241                C242                C243                C244                C245                C246               C247               C248                C249                C250                C251                C252                 C253                C254               C255               C256               C257               C258                C259                C260               C261               C262                C263               C264                C265                C266                C267                C268                C269                C270                C271                C272                C273                C274               C275               C276                C277               C278                C279               C280                C281               C282               C283               C284              C285                C286               C287               C288               C289               C290                C291                C292                C293                C294                C295                C296                C297               C298                C299                C300                C301                C302               C303               C304               C305                C306                C307               C308                C309    C310               C311               C312                C313                C314                C315               C316               C317                C318                C319                C320                C321                C322               C323                C324                C325                C326                C327               C328                C329                C330               C331               C332               C333                C334                C335                 C336                C337    C338                C339               C340                C341                C342                C343               C344               C345                C346                C347                C348                C349                C350                C351                C352                C353                C354                C355                C356                C357               C358              C359               C360                C361                C362               C363                C364    C365    C366                  C367                C368              C369                C370                C371               C372               C373                C374                C375                C376                C377                C378                C379                C380                C381                C382                C383                C384                C385               C386              C387               C388                C389                C390                C391                C392    C393    C394    C395                C396               C397                C398               C399               C400               C401                C402                C403                C404                C405                C406                C407                C408                C409                C410                C411                C412                C413               C414               C415               C416               C417               C418                C419                C420    C421    C422    C423                 C424               C425               C426               C427               C428               C429                C430               C431                C432                C433                C434                C435                C436                C437                C438                C439                C440                C441               C442               C443               C444                C445                C446                C447               C448                C449    C450                  C451               C452             C453               C454                C455               C456               C457               C458                C459                C460                C461               C462               C463                C464                C465                C466                C467                C468                C469               C470               C471                C472               C473                C474                C475                C476                C477    C478    C479                C480                C481                C482               C483               C484               C485                C486                C487                C488               C489              C490                C491                C492               C493                C494                C495                C496                C497               C498               C499                C500                C501                C502                C503               C504                C505    C506                  C507               C508                C509               C510               C511               C512                C513               C514                C515                C516                C517                C518                C519                C520                C521                C522                C523                C524                C525              C526              C527               C528                C529              C530                C531               C532                C533    C534                  C535                 C536               C537               C538               C539              C540               C541               C542                C543                C544                C545                C546                C547                C548                C549                C550                C551                C552                C553               C554               C555               C556                C557               C558                C559                C560    C561    C562    C563               C564                C565               C566                C567              C568               C569                C570                C571                C572                C573              C574                C575               C576                C577                C578               C579                C580               C581               C582               C583               C584                C585               C586                C587               C588    C589    C590    C591               C592                C593                C594                C595               C596               C597                C598                C599                C600                C601                C602                C603               C604                C605                C606                C607                C608               C609               C610               C611                C612                C613                C614               C615               C616    C617    C618    C619               C620                C621                C622               C623                C624              C625               C626                C627                C628                C629                C630                C631                C632                C633                C634                C635               C636               C637                C638                C639               C640                C641                C642               C643                C644    C645    C646                 C647                C648               C649               C650                C651               C652                C653               C654              C655                C656               C657                C658                C659                C660                C661               C662                C663                C664               C665               C666               C667               C668                C669               C670                C671    C672    C673    C674    C675    C676                C677               C678                C679                C680              C681                C682               C683               C684               C685               C686               C687               C688               C689              C690                C691                C692              C693               C694                C695               C696               C697               C698    C699    C700    C701    C702    C703    C704                 C705                C706               C707               C708               C709               C710             C711               C712               C713               C714               C715               C716                C717               C718                C719               C720                C721               C722                C723               C724                C725                  C726                C727    C728    C729    C730    C731    C732    C733                 C734              C735              C736                C737                C738               C739                C740               C741               C742               C743               C744               C745                C746                C747               C748                C749                C750               C751               C752                C753                   C754    C755    C756    C757    C758    C759    C760    C761    C762    C763                 C764               C765              C766               C767               C768               C769               C770               C771                C772                C773               C774               C775                C776               C777                C778                   C779    C780    C781    C782    C783    C784    C785

In [55]:
# Specify the response and predictor columns
y = 'C785'
x = list(set(train.names) - set([y]))

# Encode the response column as categorical for classification
train[y] = train[y].asfactor()
test[y] = test[y].asfactor()

In [ ]:
from h2o.estimators import H2ODeepLearningEstimator
# The example below illustrates the relative simplicity underlying most H2O Deep Learning model parameter
# configurations, as a result of the default settings. Rectified linear activation is popular
# with image processing and has performed well on the MNIST database previously and dropout has been
# known to enhance performance on this dataset as well, so we train our model accordingly.

# Train a Deep Learning model and validate on a test set.

# Train the deep learning model
model = H2ODeepLearningEstimator(
    distribution='multinomial',
    activation='RectifierWithDropout',
    hidden=[200, 200, 200], # 784-200-200-200-10
    input_dropout_ratio=0.2, # 784 * 200 + 200 + 200 * 200 + 200 + 200 * 200 +200 + 200 * 10 + 10 =  239 410 parameters
    l1=1e-5,
    epochs=10,
    variable_importances=True
)

model.train(x=x, y=y, training_frame=train, validation_frame=test)

deeplearning Model Build progress: |

/Users/mikolaj.mlodzikowski/.pyenv/versions/3.14.0/lib/python3.14/site-packages/h2o/estimators/estimator_base.py:192: RuntimeWarning: Dropping bad and constant columns: [C86, C85, C729, C728, C646, C645, C169, C760, C561, C53, C11, C55, C10, C54, C57, C12, C56, C58, C17, C19, C18, C731, C730, C20, C22, C21, C24, C23, C26, C25, C28, C27, C702, C701, C29, C700, C1, C2, C784, C3, C783, C4, C782, C5, C781, C6, C142, C7, C141, C8, C9, C31, C30, C32, C759, C758, C757, C756, C755, C477, C113, C674, C112, C673, C672, C84, C83]
  warnings.warn(mesg["message"], RuntimeWarning)

█████████████████████████████████████████████| (done) 100%

Model Details
=============
H2ODeepLearningEstimator : Deep Learning
Model Key: DeepLearning_model_python_1772973862355_37


Status of Neuron Layers: predicting C785, 10-class classification, multinomial distribution, CrossEntropy loss, 226,010 weights/biases, 2.8 MB, 600,000 training samples, mini-batch size 1
    layer    units    type              dropout    l1     l2    mean_rate    rate_rms     momentum    mean_weight    weight_rms    mean_bias    bias_rms
--  -------  -------  ----------------  ---------  -----  ----  -----------  -----------  ----------  -------------  ------------  -----------  ----------
    1        717      Input             20
    2        200      RectifierDropout  50         1e-05  0     0.0757699    0.172771     0           0.0206866      0.0738326     0.0636054    0.124588
    3        200      RectifierDropout  50         1e-05  0     0.000943004  0.000389616  0           -0.016792      0.0751466     0.906209     0.069507
    4        200      RectifierDropout  50         1e-05  0     0.0013151    0.000729393  0           -0.0202296     0.0732095     0.797011     0.0498724
    5        10       Softmax                      1e-05  0     0.00733712   0.0159974    0           -0.191204      0.432748      -1.37275     0.248851

ModelMetricsMultinomial: deeplearning
** Reported on train data. **

MSE: 0.027853957426979783
RMSE: 0.1668950491386122
LogLoss: 0.10240377738466502
Mean Per-Class Error: 0.03346216510463055
AUC table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).
AUCPR table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class
0     1     2     3     4    5    6     7     8    9     Error      Rate
----  ----  ----  ----  ---  ---  ----  ----  ---  ----  ---------  -----------
993   1     5     0     0    1    6     0     2    3     0.0178042  18 / 1,011
1     1060  11    1     1    0    1     0     0    0     0.0139535  15 / 1,075
2     3     952   4     4    2    4     2     5    0     0.0265849  26 / 978
1     1     22    989   0    14   0     6     13   5     0.0589914  62 / 1,051
2     2     6     0     888  0    5     2     3    27    0.0502674  47 / 935
8     0     2     10    1    881  3     1     5    5     0.0382096  35 / 916
6     0     2     0     2    9    1007  0     0    0     0.0185185  19 / 1,026
4     2     9     1     3    2    0     1002  0    6     0.0262391  27 / 1,029
1     7     6     5     0    12   4     0     920  7     0.043659   42 / 962
3     2     0     7     9    3    0     15    2    974   0.0403941  41 / 1,015
1021  1078  1015  1017  908  924  1030  1028  950  1027  0.0332066  332 / 9,998

Top-10 Hit Ratios:
k    hit_ratio
---  -----------
1    0.966793
2    0.991798
3    0.996899
4    0.9983
5    0.9991
6    0.9996
7    0.9996
8    0.9998
9    0.9999
10   1

ModelMetricsMultinomial: deeplearning
** Reported on validation data. **

MSE: 0.02992528705706295
RMSE: 0.17298926861820924
LogLoss: 0.12068007210180112
Mean Per-Class Error: 0.0348249634968996
AUC table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).
AUCPR table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class
0    1     2     3     4    5    6    7     8    9     Error      Rate
---  ----  ----  ----  ---  ---  ---  ----  ---  ----  ---------  ------------
966  0     1     2     0    2    5    1     1    2     0.0142857  14 / 980
0    1123  5     1     0    0    3    0     3    0     0.0105727  12 / 1,135
6    0     991   8     5    1    9    6     4    2     0.0397287  41 / 1,032
0    0     12    976   0    8    0    9     4    1     0.0336634  34 / 1,010
1    0     6     0     946  1    7    2     2    17    0.0366599  36 / 982
3    0     0     12    2    854  8    3     7    3     0.0426009  38 / 892
7    3     1     1     4    7    931  0     4    0     0.0281837  27 / 958
2    11    15    4     1    0    0    980   0    15    0.0466926  48 / 1,028
2    2     6     7     5    11   4    6     926  5     0.0492813  48 / 974
4    6     3     9     12   2    0    7     4    962   0.0465808  47 / 1,009
991  1145  1040  1020  975  886  967  1014  955  1007  0.0345     345 / 10,000

Top-10 Hit Ratios:
k    hit_ratio
---  -----------
1    0.9655
2    0.9879
3    0.9952
4    0.9978
5    0.9991
6    0.9994
7    0.9997
8    0.9999
9    1
10   1

Scoring History:
    timestamp            duration    training_speed    epochs    iterations    samples    training_rmse    training_logloss    training_r2    training_classification_error    training_auc    training_pr_auc    validation_rmse    validation_logloss    validation_r2    validation_classification_error    validation_auc    validation_pr_auc
--  -------------------  ----------  ----------------  --------  ------------  ---------  ---------------  ------------------  -------------  -------------------------------  --------------  -----------------  -----------------  --------------------  ---------------  ---------------------------------  ----------------  -------------------
    2026-03-08 15:10:24  0.000 sec                     0         0             0          nan              nan                 nan            nan                              nan             nan                nan                nan                   nan              nan                                nan               nan
    2026-03-08 15:10:26  2.217 sec   38986 obs/sec     1         1             60000      0.251894         0.248153            0.992416       0.075215                         nan             nan                0.245739           0.240088              0.992798         0.0696                             nan               nan
    2026-03-08 15:10:31  7.345 sec   46497 obs/sec     5         5             300000     0.193909         0.140332            0.995506       0.045109                         nan             nan                0.193315           0.15233               0.995543         0.0428                             nan               nan
    2026-03-08 15:10:36  12.308 sec  48000 obs/sec     9         9             540000     0.169591         0.105962            0.996562       0.0334067                        nan             nan                0.174609           0.123592              0.996364         0.0352                             nan               nan
    2026-03-08 15:10:37  13.628 sec  48410 obs/sec     10        10            600000     0.166895         0.102404            0.996671       0.0332066                        nan             nan                0.172989           0.12068               0.996431         0.0345                             nan               nan

Variable Importances:
variable    relative_importance    scaled_importance     percentage
----------  ---------------------  --------------------  ----------------------
C77         1.0                    1.0                   0.0030221036220983203
C76         0.9444424510002136     0.9444424510002136    0.002854202952031161
C78         0.9389175772666931     0.9389175772666931    0.002837506211109453
C770        0.9257474541664124     0.9257474541664124    0.0027977047343846137
C772        0.9207284450531006     0.9207284450531006    0.0027825367687639296
C75         0.9162399768829346     0.9162399768829346    0.002768972152849198
C769        0.9142653346061707     0.9142653346061707    0.002763004579272241
C773        0.9030117392539978     0.9030117392539978    0.0027289950479968106
C295        0.8791865110397339     0.8791865110397339    0.0026569927395131646
C74         0.8782039880752563     0.8782039880752563    0.0026540234533034223
---         ---                    ---                   ---
C16         0.010499405674636364   0.010499405674636364  3.1730291919198215e-05
C15         0.010302300564944744   0.010302300564944744  3.113461985326508e-05
C365        0.010239636525511742   0.010239636525511742  3.09452426327193e-05
C533        0.010164439678192139   0.010164439678192139  3.071798996806435e-05
C197        0.010046826675534248   0.010046826675534248  3.036255128672608e-05
C59         0.01003941148519516    0.01003941148519516   3.0340141813143772e-05
C732        0.010005290620028973   0.010005290620028973  3.0237025022935908e-05
C754        0.009952393360435963   0.009952393360435963  3.0077164023120796e-05
C617        0.009487086907029152   0.009487086907029152  2.8670959704894352e-05
C727        0.00946663785725832    0.00946663785725832   2.860916055751345e-05
[717 rows x 4 columns]


[tips]
Use `model.explain()` to inspect the model.
--
Use `h2o.display.toggle_user_tips()` to switch on/off this section.

In [57]:
# View the specified parameters
print("Model parameters: ", model.params)

Model parameters:  {'model_id': {'default': None, 'actual': {'__meta': {'schema_version': 3, 'schema_name': 'ModelKeyV3', 'schema_type': 'Key<Model>'}, 'name': 'DeepLearning_model_python_1717403639876_65', 'type': 'Key<Model>', 'URL': '/3/Models/DeepLearning_model_python_1717403639876_65'}, 'input': None}, 'training_frame': {'default': None, 'actual': {'__meta': {'schema_version': 3, 'schema_name': 'FrameKeyV3', 'schema_type': 'Key<Frame>'}, 'name': 'py_33_sid_a081', 'type': 'Key<Frame>', 'URL': '/3/Frames/py_33_sid_a081'}, 'input': {'__meta': {'schema_version': 3, 'schema_name': 'FrameKeyV3', 'schema_type': 'Key<Frame>'}, 'name': 'py_33_sid_a081', 'type': 'Key<Frame>', 'URL': '/3/Frames/py_33_sid_a081'}}, 'validation_frame': {'default': None, 'actual': {'__meta': {'schema_version': 3, 'schema_name': 'FrameKeyV3', 'schema_type': 'Key<Frame>'}, 'name': 'py_34_sid_a081', 'type': 'Key<Frame>', 'URL': '/3/Frames/py_34_sid_a081'}, 'input': {'__meta': {'schema_version': 3, 'schema_name': 'FrameKeyV3', 'schema_type': 'Key<Frame>'}, 'name': 'py_34_sid_a081', 'type': 'Key<Frame>', 'URL': '/3/Frames/py_34_sid_a081'}}, 'nfolds': {'default': 0, 'actual': 0, 'input': 0}, 'keep_cross_validation_models': {'default': True, 'actual': True, 'input': True}, 'keep_cross_validation_predictions': {'default': False, 'actual': False, 'input': False}, 'keep_cross_validation_fold_assignment': {'default': False, 'actual': False, 'input': False}, 'fold_assignment': {'default': 'AUTO', 'actual': None, 'input': 'AUTO'}, 'fold_column': {'default': None, 'actual': None, 'input': None}, 'response_column': {'default': None, 'actual': {'__meta': {'schema_version': 3, 'schema_name': 'ColSpecifierV3', 'schema_type': 'VecSpecifier'}, 'column_name': 'C785', 'is_member_of_frames': None}, 'input': {'__meta': {'schema_version': 3, 'schema_name': 'ColSpecifierV3', 'schema_type': 'VecSpecifier'}, 'column_name': 'C785', 'is_member_of_frames': None}}, 'ignored_columns': {'default': None, 'actual': None, 'input': None}, 'ignore_const_cols': {'default': True, 'actual': True, 'input': True}, 'score_each_iteration': {'default': False, 'actual': False, 'input': False}, 'weights_column': {'default': None, 'actual': None, 'input': None}, 'offset_column': {'default': None, 'actual': None, 'input': None}, 'balance_classes': {'default': False, 'actual': False, 'input': False}, 'class_sampling_factors': {'default': None, 'actual': None, 'input': None}, 'max_after_balance_size': {'default': 5.0, 'actual': 5.0, 'input': 5.0}, 'max_confusion_matrix_size': {'default': 20, 'actual': 20, 'input': 20}, 'checkpoint': {'default': None, 'actual': None, 'input': None}, 'pretrained_autoencoder': {'default': None, 'actual': None, 'input': None}, 'overwrite_with_best_model': {'default': True, 'actual': True, 'input': True}, 'use_all_factor_levels': {'default': True, 'actual': True, 'input': True}, 'standardize': {'default': True, 'actual': True, 'input': True}, 'activation': {'default': 'Rectifier', 'actual': 'RectifierWithDropout', 'input': 'RectifierWithDropout'}, 'hidden': {'default': [200, 200], 'actual': [200, 200, 200], 'input': [200, 200, 200]}, 'epochs': {'default': 10.0, 'actual': 10.0, 'input': 10.0}, 'train_samples_per_iteration': {'default': -2, 'actual': -2, 'input': -2}, 'target_ratio_comm_to_comp': {'default': 0.05, 'actual': 0.05, 'input': 0.05}, 'seed': {'default': -1, 'actual': 5419331722423643436, 'input': -1}, 'adaptive_rate': {'default': True, 'actual': True, 'input': True}, 'rho': {'default': 0.99, 'actual': 0.99, 'input': 0.99}, 'epsilon': {'default': 1e-08, 'actual': 1e-08, 'input': 1e-08}, 'rate': {'default': 0.005, 'actual': 0.005, 'input': 0.005}, 'rate_annealing': {'default': 1e-06, 'actual': 1e-06, 'input': 1e-06}, 'rate_decay': {'default': 1.0, 'actual': 1.0, 'input': 1.0}, 'momentum_start': {'default': 0.0, 'actual': 0.0, 'input': 0.0}, 'momentum_ramp': {'default': 1000000.0, 'actual': 1000000.0, 'input': 1000000.0}, 'momentum_stable': {'default': 0.0, 'actual': 0.0, 'input': 0.0}, 'nesterov_accelerated_gradient': {'default': True, 'actual': True, 'input': True}, 'input_dropout_ratio': {'default': 0.0, 'actual': 0.2, 'input': 0.2}, 'hidden_dropout_ratios': {'default': None, 'actual': None, 'input': None}, 'l1': {'default': 0.0, 'actual': 1e-05, 'input': 1e-05}, 'l2': {'default': 0.0, 'actual': 0.0, 'input': 0.0}, 'max_w2': {'default': 3.4028235e+38, 'actual': 3.4028235e+38, 'input': 3.4028235e+38}, 'initial_weight_distribution': {'default': 'UniformAdaptive', 'actual': 'UniformAdaptive', 'input': 'UniformAdaptive'}, 'initial_weight_scale': {'default': 1.0, 'actual': 1.0, 'input': 1.0}, 'initial_weights': {'default': None, 'actual': None, 'input': None}, 'initial_biases': {'default': None, 'actual': None, 'input': None}, 'loss': {'default': 'Automatic', 'actual': 'Automatic', 'input': 'Automatic'}, 'distribution': {'default': 'AUTO', 'actual': 'multinomial', 'input': 'multinomial'}, 'quantile_alpha': {'default': 0.5, 'actual': 0.5, 'input': 0.5}, 'tweedie_power': {'default': 1.5, 'actual': 1.5, 'input': 1.5}, 'huber_alpha': {'default': 0.9, 'actual': 0.9, 'input': 0.9}, 'score_interval': {'default': 5.0, 'actual': 5.0, 'input': 5.0}, 'score_training_samples': {'default': 10000, 'actual': 10000, 'input': 10000}, 'score_validation_samples': {'default': 0, 'actual': 0, 'input': 0}, 'score_duty_cycle': {'default': 0.1, 'actual': 0.1, 'input': 0.1}, 'classification_stop': {'default': 0.0, 'actual': 0.0, 'input': 0.0}, 'regression_stop': {'default': 1e-06, 'actual': 1e-06, 'input': 1e-06}, 'stopping_rounds': {'default': 5, 'actual': 5, 'input': 5}, 'stopping_metric': {'default': 'AUTO', 'actual': 'logloss', 'input': 'AUTO'}, 'stopping_tolerance': {'default': 0.0, 'actual': 0.0, 'input': 0.0}, 'max_runtime_secs': {'default': 0.0, 'actual': 0.0, 'input': 0.0}, 'score_validation_sampling': {'default': 'Uniform', 'actual': 'Uniform', 'input': 'Uniform'}, 'diagnostics': {'default': True, 'actual': True, 'input': True}, 'fast_mode': {'default': True, 'actual': True, 'input': True}, 'force_load_balance': {'default': True, 'actual': True, 'input': True}, 'variable_importances': {'default': True, 'actual': True, 'input': True}, 'replicate_training_data': {'default': True, 'actual': True, 'input': True}, 'single_node_mode': {'default': False, 'actual': False, 'input': False}, 'shuffle_training_data': {'default': False, 'actual': False, 'input': False}, 'missing_values_handling': {'default': 'MeanImputation', 'actual': 'MeanImputation', 'input': 'MeanImputation'}, 'quiet_mode': {'default': False, 'actual': False, 'input': False}, 'autoencoder': {'default': False, 'actual': False, 'input': False}, 'sparse': {'default': False, 'actual': False, 'input': False}, 'col_major': {'default': False, 'actual': False, 'input': False}, 'average_activation': {'default': 0.0, 'actual': 0.0, 'input': 0.0}, 'sparsity_beta': {'default': 0.0, 'actual': 0.0, 'input': 0.0}, 'max_categorical_features': {'default': 2147483647, 'actual': 2147483647, 'input': 2147483647}, 'reproducible': {'default': False, 'actual': False, 'input': False}, 'export_weights_and_biases': {'default': False, 'actual': False, 'input': False}, 'mini_batch_size': {'default': 1, 'actual': 1, 'input': 1}, 'categorical_encoding': {'default': 'AUTO', 'actual': 'OneHotInternal', 'input': 'AUTO'}, 'elastic_averaging': {'default': False, 'actual': False, 'input': False}, 'elastic_averaging_moving_rate': {'default': 0.9, 'actual': 0.9, 'input': 0.9}, 'elastic_averaging_regularization': {'default': 0.001, 'actual': 0.001, 'input': 0.001}, 'export_checkpoints_dir': {'default': None, 'actual': None, 'input': None}, 'auc_type': {'default': 'AUTO', 'actual': 'AUTO', 'input': 'AUTO'}, 'custom_metric_func': {'default': None, 'actual': None, 'input': None}, 'gainslift_bins': {'default': -1, 'actual': -1, 'input': -1}}

In [ ]:
# Display all performance metrics
print("Model performance: ", model)

In [59]:
# Training set metrics
train_perf = model.model_performance(train)
print("Training performance: ", train_perf)

Training performance:  ModelMetricsMultinomial: deeplearning
** Reported on test data. **

MSE: 0.024053370982466692
RMSE: 0.15509149229556948
LogLoss: 0.0911854682473896
Mean Per-Class Error: 0.028490943953264986
AUC table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).
AUCPR table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class
0     1     2     3     4     5     6     7     8     9     Error      Rate
----  ----  ----  ----  ----  ----  ----  ----  ----  ----  ---------  --------------
5844  1     19    6     3     8     21    2     13    6     0.0133378  79 / 5,923
1     6640  52    9     5     3     1     14    15    2     0.015129   102 / 6,742
13    7     5812  26    24    3     18    26    25    4     0.0245049  146 / 5,958
1     1     87    5870  4     69    2     42    39    16    0.0425705  261 / 6,131
3     11    25    0     5678  3     25    8     13    76    0.0280726  164 / 5,842
14    4     16    74    12    5214  40    5     26    16    0.0381848  207 / 5,421
24    7     19    1     13    34    5812  0     8     0     0.0179115  106 / 5,918
7     17    37    5     31    1     0     6126  5     36    0.0221868  139 / 6,265
11    35    31    42    12    53    18    6     5622  21    0.0391386  229 / 5,851
13    10    5     39    73    17    1     84    19    5688  0.0438729  261 / 5,949
5931  6733  6103  6072  5855  5405  5938  6313  5785  5865  0.0282333  1,694 / 60,000

Top-10 Hit Ratios:
k    hit_ratio
---  -----------
1    0.971767
2    0.992317
3    0.997
4    0.9986
5    0.99925
6    0.999633
7    0.9998
8    0.999917
9    0.999967
10   1

In [60]:
# Validation set metrics
valid_perf = model.model_performance(test)
print("Validation performance: ", valid_perf)

Validation performance:  ModelMetricsMultinomial: deeplearning
** Reported on test data. **

MSE: 0.028610970731963618
RMSE: 0.1691477777919758
LogLoss: 0.11646824606917394
Mean Per-Class Error: 0.03300755699704586
AUC table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).
AUCPR table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class
0    1     2     3     4    5    6    7     8    9    Error       Rate
---  ----  ----  ----  ---  ---  ---  ----  ---  ---  ----------  ------------
968  0     1     2     1    2    3    1     2    0    0.0122449   12 / 980
0    1125  6     0     0    0    3    0     1    0    0.00881057  10 / 1,135
6    1     994   8     4    0    4    8     5    2    0.0368217   38 / 1,032
0    0     11    976   0    6    1    9     7    0    0.0336634   34 / 1,010
1    0     7     0     947  0    11   3     3    10   0.0356415   35 / 982
3    0     2     16    2    850  7    1     9    2    0.0470852   42 / 892
8    3     1     1     6    5    932  0     2    0    0.0271399   26 / 958
2    6     13    2     1    0    0    993   0    11   0.0340467   35 / 1,028
3    1     6     7     3    10   3    7     933  1    0.0420945   41 / 974
5    6     1     10    18   0    0    11    2    956  0.0525273   53 / 1,009
996  1142  1042  1022  982  873  964  1033  964  982  0.0326      326 / 10,000

Top-10 Hit Ratios:
k    hit_ratio
---  -----------
1    0.9674
2    0.9889
3    0.9948
4    0.9981
5    0.9991
6    0.9994
7    0.9996
8    0.9997
9    0.9999
10   1

In [66]:
# Get MSE only for validation set
mse_valid = valid_perf.mse()
print("Validation MSE: ", mse_valid)

Validation MSE:  0.028610970731963618

In [62]:
# Variable importance
var_importance = model.varimp()
print("Variable importance: ", var_importance)

Variable importance:  [('C76', 1.0, 1.0, 0.0029891531397159402), ('C78', 0.9820566177368164, 0.9820566177368164, 0.0029355176222868214), ('C77', 0.9753942489624023, 0.9753942489624023, 0.0029156027817468363), ('C770', 0.9691189527511597, 0.9691189527511597, 0.0028968449603743525), ('C769', 0.9617758989334106, 0.9617758989334106, 0.002874895447999925), ('C768', 0.9557488560676575, 0.9557488560676575, 0.0028568796938945565), ('C773', 0.949530839920044, 0.949530839920044, 0.002838293091404113), ('C75', 0.9327151775360107, 0.9327151775360107, 0.002788028501392477), ('C771', 0.8955176472663879, 0.8955176472663879, 0.002676839386997355), ('C772', 0.8902101516723633, 0.8902101516723633, 0.0026609744698784478), ('C295', 0.885613203048706, 0.885613203048706, 0.0026472334864669302), ('C767', 0.8789734840393066, 0.8789734840393066, 0.002627386349543152), ('C323', 0.8760762214660645, 0.8760762214660645, 0.0026187259880257638), ('C774', 0.862788736820221, 0.862788736820221, 0.0025790076615777135), ('C74', 0.8499899506568909, 0.8499899506568909, 0.0025407501297330425), ('C283', 0.8384130597114563, 0.8384130597114563, 0.0025061450298153477), ('C586', 0.8116911053657532, 0.8116911053657532, 0.002426269016083543), ('C766', 0.8086795210838318, 0.8086795210838318, 0.0024172669294717187), ('C351', 0.7987663149833679, 0.7987663149833679, 0.0023876348383318658), ('C255', 0.7957316637039185, 0.7957316637039185, 0.0023785638009319564), ('C322', 0.7944291234016418, 0.7944291234016418, 0.0023746703084977995), ('C73', 0.7930260300636292, 0.7930260300636292, 0.0023704762476411644), ('C79', 0.7903978228569031, 0.7903978228569031, 0.0023626201338173554), ('C349', 0.7861368060112, 0.7861368060112, 0.0023498833019346393), ('C517', 0.7856523394584656, 0.7856523394584656, 0.002348435157217446), ('C294', 0.7809338569641113, 0.7809338569641113, 0.0023343308904547524), ('C348', 0.7798932790756226, 0.7798932790756226, 0.002331220443792257), ('C350', 0.779802143573761, 0.779802143573761, 0.0023309480258207277), ('C321', 0.7781866192817688, 0.7781866192817688, 0.0023261189763110323), ('C267', 0.7713404893875122, 0.7713404893875122, 0.002305654845642712), ('C544', 0.7695543169975281, 0.7695543169975281, 0.0023003157028351168), ('C377', 0.7568181157112122, 0.7568181157112122, 0.0022622452467720715), ('C227', 0.7564691305160522, 0.7564691305160522, 0.0022612020765802447), ('C434', 0.7537291049957275, 0.7537291049957275, 0.0022530117206932643), ('C297', 0.7460497617721558, 0.7460497617721558, 0.0022300569877855684), ('C378', 0.7442562580108643, 0.7442562580108643, 0.0022246959303864116), ('C545', 0.7427575588226318, 0.7427575588226318, 0.002220216089002417), ('C558', 0.7376387715339661, 0.7376387715339661, 0.0022049152499069636), ('C531', 0.7371631860733032, 0.7371631860733032, 0.00220349365213402), ('C461', 0.7364164590835571, 0.7364164590835571, 0.00220126157080811), ('C559', 0.7355115413665771, 0.7355115413665771, 0.0021985566331732148), ('C462', 0.7350916266441345, 0.7350916266441345, 0.0021973014437622123), ('C488', 0.7343606948852539, 0.7343606948852539, 0.002195116576800236), ('C404', 0.7342735528945923, 0.7342735528945923, 0.002194856096045249), ('C324', 0.7327385544776917, 0.7327385544776917, 0.0021902677507079113), ('C268', 0.7327225208282471, 0.7327225208282471, 0.002190219823674333), ('C741', 0.7304666042327881, 0.7304666042327881, 0.0021834765435000793), ('C489', 0.7285370826721191, 0.7285370826721191, 0.002177708908068856), ('C266', 0.7246974110603333, 0.7246974110603333, 0.0021662315416150083), ('C311', 0.722743570804596, 0.722743570804596, 0.002160391213880068), ('C614', 0.7207807302474976, 0.7207807302474976, 0.0021545239828660552), ('C72', 0.7154187560081482, 0.7154187560081482, 0.002138496220733428), ('C775', 0.7145037055015564, 0.7145037055015564, 0.0021357609946386505), ('C68', 0.7126161456108093, 0.7126161456108093, 0.002130118789064822), ('C490', 0.7070082426071167, 0.7070082426071167, 0.002113355908194112), ('C352', 0.7069413065910339, 0.7069413065910339, 0.002113155826191478), ('C591', 0.7069308161735535, 0.7069308161735535, 0.0021131244687271292), ('C40', 0.7047800421714783, 0.7047800421714783, 0.0021066954758660068), ('C296', 0.703884482383728, 0.703884482383728, 0.00210401851051465), ('C460', 0.7002944946289062, 0.7002944946289062, 0.0020932874873457828), ('C293', 0.7000100016593933, 0.7000100016593933, 0.002092437094292736), ('C270', 0.6997888684272766, 0.6997888684272766, 0.002091776093197659), ('C486', 0.699370801448822, 0.699370801448822, 0.0020905264269763997), ('C648', 0.6986808776855469, 0.6986808776855469, 0.002088464139193241), ('C41', 0.6973545551300049, 0.6973545551300049, 0.002084499557962067), ('C516', 0.6963346004486084, 0.6963346004486084, 0.0020814507572238026), ('C298', 0.6962615847587585, 0.6962615847587585, 0.002081232502145239), ('C619', 0.6946426033973694, 0.6946426033973694, 0.002076393118925701), ('C518', 0.6945183277130127, 0.6945183277130127, 0.0020760216398736163), ('C380', 0.6944782137870789, 0.6944782137870789, 0.0020759017332059645), ('C71', 0.6942738890647888, 0.6942738890647888, 0.00207529097532081), ('C318', 0.693250298500061, 0.693250298500061, 0.00207223130637047), ('C515', 0.6925070285797119, 0.6925070285797119, 0.002070009558754402), ('C376', 0.691497266292572, 0.691497266292572, 0.0020669912246434313), ('C405', 0.6905931234359741, 0.6905931234359741, 0.0020642886031848797), ('C563', 0.6891143918037415, 0.6891143918037415, 0.0020598684478835942), ('C407', 0.6866261959075928, 0.6866261959075928, 0.002052430849308393), ('C325', 0.686565101146698, 0.686565101146698, 0.002052248227712044), ('C65', 0.6843201518058777, 0.6843201518058777, 0.002045537730341428), ('C406', 0.6831568479537964, 0.6831568479537964, 0.0020420604369795355), ('C379', 0.6828716397285461, 0.6828716397285461, 0.002041207905917556), ('C69', 0.6824579238891602, 0.6824579238891602, 0.002039971245917305), ('C320', 0.6816110610961914, 0.6816110610961914, 0.002037439843340794), ('C742', 0.6815420389175415, 0.6815420389175415, 0.0020372335254787727), ('C347', 0.6791771054267883, 0.6791771054267883, 0.0020301643771096682), ('C435', 0.6791644096374512, 0.6791644096374512, 0.00203012642745111), ('C491', 0.6774566769599915, 0.6774566769599915, 0.002025021752956486), ('C487', 0.6773952841758728, 0.6773952841758728, 0.0020248382405230816), ('C457', 0.6731691360473633, 0.6731691360473633, 0.002012205636575843), ('C42', 0.6723542213439941, 0.6723542213439941, 0.0020097697317316664), ('C375', 0.6680207848548889, 0.6680207848548889, 0.0019968164264444976), ('C463', 0.6678566336631775, 0.6678566336631775, 0.001996325753394405), ('C269', 0.6670966744422913, 0.6670966744422913, 0.0019940541189032374), ('C587', 0.6668574213981628, 0.6668574213981628, 0.001993338954915194), ('C70', 0.6627289056777954, 0.6627289056777954, 0.001980998189187291), ('C354', 0.6618592143058777, 0.6618592143058777, 0.0019783985484923394), ('C212', 0.6608418226242065, 0.6608418226242065, 0.0019753574089527515), ('C43', 0.6608380675315857, 0.6608380675315857, 0.0019753461844058537), ('C739', 0.6603715419769287, 0.6603715419769287, 0.0019739516680793933), ('C543', 0.6602848172187805, 0.6602848172187805, 0.0019736924344962836), ('C737', 0.6600018739700317, 0.6600018739700317, 0.0019728466737959248), ('C458', 0.6594876050949097, 0.6594876050949097, 0.0019713094453731954), ('C339', 0.6590110063552856, 0.6590110063552856, 0.0019698848187542635), ('C738', 0.6564621329307556, 0.6564621329307556, 0.001962265845754591), ('C401', 0.6563789248466492, 0.6563789248466492, 0.0019620171240487343), ('C292', 0.6561601161956787, 0.6561601161956787, 0.001961363071482689), ('C291', 0.6550030708312988, 0.6550030708312988, 0.0019579044856989592), ('C271', 0.6541711688041687, 0.6541711688041687, 0.001955417803142627), ('C432', 0.6541112661361694, 0.6541112661361694, 0.0019552387448944996), ('C433', 0.6538531184196472, 0.6538531184196472, 0.001954467101837147), ('C67', 0.6508954763412476, 0.6508954763412476, 0.0019456262567323426), ('C299', 0.6494391560554504, 0.6494391560554504, 0.00194127309237762), ('C353', 0.6492404341697693, 0.6492404341697693, 0.001940679082229106), ('C66', 0.6488902568817139, 0.6488902568817139, 0.0019396323486890578), ('C300', 0.6486284732818604, 0.6486284732818604, 0.0019388498374196296), ('C319', 0.645396888256073, 0.645396888256073, 0.0019291901348935383), ('C211', 0.645363986492157, 0.645363986492157, 0.0019290917864826266), ('C765', 0.6438943147659302, 0.6438943147659302, 0.001924698712627824), ('C507', 0.6415390372276306, 0.6415390372276306, 0.0019176584273793134), ('C402', 0.6414840221405029, 0.6414840221405029, 0.001917493978858894), ('C503', 0.6405007839202881, 0.6405007839202881, 0.00191455492924585), ('C272', 0.6386148929595947, 0.6386148929595947, 0.0019089177123595316), ('C744', 0.637195348739624, 0.637195348739624, 0.0019046744772974406), ('C571', 0.6370922923088074, 0.6370922923088074, 0.0019043664258436971), ('C546', 0.6359848380088806, 0.6359848380088806, 0.001901056075345979), ('C381', 0.6358888745307922, 0.6358888745307922, 0.001900769225814153), ('C264', 0.6322059035301208, 0.6322059035301208, 0.0018897602614840134), ('C475', 0.6321503520011902, 0.6321503520011902, 0.0018895942094568944), ('C535', 0.6303590536117554, 0.6303590536117554, 0.0018842397442519472), ('C403', 0.6295905113220215, 0.6295905113220215, 0.0018819424536535847), ('C214', 0.6295578479766846, 0.6295578479766846, 0.0018818448179123172), ('C642', 0.6294638514518738, 0.6294638514518738, 0.0018815638479050567), ('C408', 0.6286166906356812, 0.6286166906356812, 0.00187903155449149), ('C431', 0.6281102895736694, 0.6281102895736694, 0.0018775178441670223), ('C301', 0.6278976202011108, 0.6278976202011108, 0.0018768821428443174), ('C239', 0.6271445155143738, 0.6271445155143738, 0.0018746309976054225), ('C438', 0.6263587474822998, 0.6263587474822998, 0.0018722822166252601), ('C265', 0.6245614886283875, 0.6245614886283875, 0.0018669099346792057), ('C743', 0.6237787008285522, 0.6237787008285522, 0.001864570062069597), ('C326', 0.6201508045196533, 0.6201508045196533, 0.001853725724427288), ('C736', 0.6200875043869019, 0.6200875043869019, 0.0018535365106367295), ('C492', 0.619583785533905, 0.619583785533905, 0.0018520308178457598), ('C238', 0.619019091129303, 0.619019091129303, 0.0018503428597932635), ('C740', 0.6189512610435486, 0.6189512610435486, 0.0018501401052794637), ('C327', 0.6149371862411499, 0.6149371862411499, 0.001838141420980819), ('C459', 0.6147732734680176, 0.6147732734680176, 0.001837651460600371), ('C400', 0.6147670149803162, 0.6147670149803162, 0.0018376327530222085), ('C437', 0.6135401725769043, 0.6135401725769043, 0.001833965533200113), ('C430', 0.6134955883026123, 0.6134955883026123, 0.0018338322639766312), ('C514', 0.6113967299461365, 0.6113967299461365, 0.0018275584549305526), ('C210', 0.6113187670707703, 0.6113187670707703, 0.0018273254119568704), ('C372', 0.6109514236450195, 0.6109514236450195, 0.0018262273662024335), ('C573', 0.6079283356666565, 0.6079283356666565, 0.0018171908932802722), ('C676', 0.6077137589454651, 0.6077137589454651, 0.001816549490600413), ('C374', 0.6076685190200806, 0.6076685190200806, 0.0018164142615354094), ('C184', 0.6070764064788818, 0.6070764064788818, 0.00181464434647382), ('C485', 0.606459379196167, 0.606459379196167, 0.0018127999574344025), ('C464', 0.6041695475578308, 0.6041695475578308, 0.001805955300003249), ('C542', 0.6031551361083984, 0.6031551361083984, 0.0018029230688342143), ('C242', 0.6029035449028015, 0.6029035449028015, 0.0018021710241920793), ('C356', 0.5995734930038452, 0.5995734930038452, 0.0017922169891028971), ('C183', 0.597555935382843, 0.597555935382843, 0.0017861862004055207), ('C345', 0.5966416001319885, 0.5966416001319885, 0.0017834531123196759), ('C64', 0.5958846211433411, 0.5958846211433411, 0.0017811903861990614), ('C572', 0.5958481431007385, 0.5958481431007385, 0.0017810813477434854), ('C241', 0.5957252383232117, 0.5957252383232117, 0.0017807139665418548), ('C243', 0.5941584706306458, 0.5941584706306458, 0.001776030657974416), ('C240', 0.5940331816673279, 0.5940331816673279, 0.0017756561500763424), ('C185', 0.5927535891532898, 0.5927535891532898, 0.0017718312520954487), ('C429', 0.5919932126998901, 0.5919932126998901, 0.001769558370432403), ('C465', 0.5901782512664795, 0.5901782512664795, 0.0017641331727652602), ('C576', 0.5891281366348267, 0.5891281366348267, 0.0017609942193169935), ('C182', 0.5890699028968811, 0.5890699028968811, 0.001760820149756376), ('C195', 0.5888911485671997, 0.5888911485671997, 0.0017602858256905711), ('C519', 0.5882500410079956, 0.5882500410079956, 0.0017583694570170805), ('C215', 0.5877542495727539, 0.5877542495727539, 0.0017568874604917835), ('C344', 0.5867510437965393, 0.5867510437965393, 0.0017538887247960306), ('C91', 0.5866878032684326, 0.5866878032684326, 0.001753699689172883), ('C330', 0.5864601731300354, 0.5864601731300354, 0.001753019267829999), ('C447', 0.5861455202102661, 0.5861455202102661, 0.0017520787220669499), ('C92', 0.5852554440498352, 0.5852554440498352, 0.0017494181481174115), ('C213', 0.5845251083374023, 0.5845251083374023, 0.0017472350628295462), ('C167', 0.5834993124008179, 0.5834993124008179, 0.001744168801684997), ('C317', 0.5834505558013916, 0.5834505558013916, 0.00174402306074274), ('C360', 0.58294278383255, 0.58294278383255, 0.0017425052525678175), ('C216', 0.5822970867156982, 0.5822970867156982, 0.0017405751650036744), ('C436', 0.5817092061042786, 0.5817092061042786, 0.001738817899828271), ('C244', 0.5808866024017334, 0.5808866024017334, 0.0017363590113880663), ('C409', 0.5806947350502014, 0.5806947350502014, 0.0017357854904918254), ('C328', 0.5805470943450928, 0.5805470943450928, 0.0017353441698146), ('C592', 0.5803356170654297, 0.5803356170654297, 0.0017347120318401167), ('C237', 0.5784898996353149, 0.5784898996353149, 0.0017291948997888607), ('C620', 0.5765164494514465, 0.5765164494514465, 0.0017232959549756774), ('C466', 0.574228048324585, 0.574228048324585, 0.0017164555735623896), ('C530', 0.5725867748260498, 0.5725867748260498, 0.0017115495557311108), ('C39', 0.5724884271621704, 0.5724884271621704, 0.001711255579502842), ('C548', 0.5717858672142029, 0.5717858672142029, 0.0017091555202285362), ('C289', 0.5700337886810303, 0.5700337886810303, 0.0017039182891800744), ('C541', 0.5699728727340698, 0.5699728727340698, 0.0017037362020859588), ('C263', 0.5697348713874817, 0.5697348713874817, 0.0017030247796135482), ('C236', 0.5688046813011169, 0.5688046813011169, 0.0017002442989963583), ('C329', 0.567817211151123, 0.567817211151123, 0.0016972925994971284), ('C547', 0.5677396059036255, 0.5677396059036255, 0.0016970606255279127), ('C745', 0.566068172454834, 0.566068172454834, 0.0016920644549866311), ('C46', 0.5655182600021362, 0.5655182600021362, 0.001690420682452081), ('C290', 0.5651987791061401, 0.5651987791061401, 0.001689465705128735), ('C355', 0.5638038516044617, 0.5638038516044617, 0.0016852960532074165), ('C513', 0.5634739398956299, 0.5634739398956299, 0.001684309896587133), ('C93', 0.5630224347114563, 0.5630224347114563, 0.0016829602784482625), ('C99', 0.562898576259613, 0.562898576259613, 0.0016825900465680548), ('C359', 0.5611225962638855, 0.5611225962638855, 0.001677281370387753), ('C373', 0.5605043768882751, 0.5605043768882751, 0.0016754334180001142), ('C223', 0.5595462918281555, 0.5595462918281555, 0.0016725695550345427), ('C251', 0.5573464632034302, 0.5573464632034302, 0.001665993930394108), ('C187', 0.5567128658294678, 0.5567128658294678, 0.0016641000108144125), ('C346', 0.5567046999931335, 0.5567046999931335, 0.0016640756018790957), ('C484', 0.556428849697113, 0.556428849697113, 0.0016632510431006543), ('C570', 0.5555927157402039, 0.5555927157402039, 0.001660751710658136), ('C156', 0.5549294948577881, 0.5549294948577881, 0.0016587692418751378), ('C262', 0.554250955581665, 0.554250955581665, 0.001656740984067494), ('C209', 0.5539295673370361, 0.5539295673370361, 0.0016557803053869938), ('C101', 0.5538924932479858, 0.5538924932479858, 0.001655669485257307), ('C428', 0.5535326600074768, 0.5535326600074768, 0.0016545938885966652), ('C647', 0.553267776966095, 0.553267776966095, 0.0016538021126218613), ('C45', 0.5526260733604431, 0.5526260733604431, 0.0016518839622742599), ('C735', 0.5520618557929993, 0.5520618557929993, 0.0016501974295610523), ('C44', 0.551618218421936, 0.551618218421936, 0.0016488713295204434), ('C574', 0.5507161617279053, 0.5507161617279053, 0.0016461749439212795), ('C520', 0.5502263307571411, 0.5502263307571411, 0.0016447107641370897), ('C97', 0.5491915345191956, 0.5491915345191956, 0.0016416175997134685), ('C98', 0.5479633212089539, 0.5479633212089539, 0.0016379462820409185), ('C186', 0.5456880927085876, 0.5456880927085876, 0.0016311452756254778), ('C569', 0.545155942440033, 0.545155942440033, 0.001629554596979427), ('C658', 0.5431906580924988, 0.5431906580924988, 0.0016236800611015604), ('C512', 0.54264235496521, 0.54264235496521, 0.001622041099087109), ('C579', 0.5424957871437073, 0.5424957871437073, 0.0016216029854232829), ('C456', 0.5422098636627197, 0.5422098636627197, 0.0016207483163523705), ('C603', 0.5421460270881653, 0.5421460270881653, 0.0016205574990551122), ('C367', 0.5400614142417908, 0.5400614142417908, 0.0016143262720202797), ('C613', 0.5393019318580627, 0.5393019318580627, 0.0016120560628684), ('C410', 0.5392078161239624, 0.5392078161239624, 0.0016117747365263174), ('C95', 0.5389717817306519, 0.5389717817306519, 0.0016110691935784724), ('C181', 0.5383175611495972, 0.5383175611495972, 0.0016091136280745458), ('C302', 0.5380721092224121, 0.5380721092224121, 0.0016083799346757514), ('C47', 0.5371739864349365, 0.5371739864349365, 0.0016056953081257184), ('C470', 0.5366412401199341, 0.5366412401199341, 0.0016041028478055567), ('C208', 0.5365827083587646, 0.5365827083587646, 0.001603927887407884), ('C764', 0.5360564589500427, 0.5360564589500427, 0.001602354847335529), ('C712', 0.5355040431022644, 0.5355040431022644, 0.0016007035917697137), ('C316', 0.5345743298530579, 0.5345743298530579, 0.0015979245364918125), ('C657', 0.5340927243232727, 0.5340927243232727, 0.0015964849438103506), ('C577', 0.5333358645439148, 0.5333358645439148, 0.0015942225740245583), ('C155', 0.53294438123703, 0.53294438123703, 0.0015930523704686373), ('C235', 0.5325883626937866, 0.5325883626937866, 0.001591988176522304), ('C483', 0.532541036605835, 0.532541036605835, 0.001591846711597913), ('C493', 0.5319425463676453, 0.5319425463676453, 0.001590057732623339), ('C575', 0.5319389700889587, 0.5319389700889587, 0.0015900470425786746), ('C746', 0.5316088199615479, 0.5316088199615479, 0.0015890601732887466), ('C511', 0.5313801169395447, 0.5313801169395447, 0.0015883765449324634), ('C399', 0.5312007665634155, 0.5312007665634155, 0.0015878404391925476), ('C540', 0.5307958126068115, 0.5307958126068115, 0.0015866299698017244), ('C641', 0.529640257358551, 0.529640257358551, 0.0015831758382032714), ('C279', 0.5295641422271729, 0.5295641422271729, 0.0015829483184193324), ('C157', 0.5294779539108276, 0.5294779539108276, 0.0015826906883429223), ('C585', 0.5290560126304626, 0.5290560126304626, 0.0015814294412399435), ('C602', 0.5289267897605896, 0.5289267897605896, 0.0015810431742927394), ('C80', 0.5274394154548645, 0.5274394154548645, 0.0015765971847168483), ('C343', 0.5273633003234863, 0.5273633003234863, 0.0015763696649329093), ('C495', 0.5272834897041321, 0.5272834897041321, 0.001576131098769484), ('C273', 0.5258544683456421, 0.5258544683456421, 0.0015718595350890324), ('C387', 0.5254927277565002, 0.5254927277565002, 0.0015707782370712364), ('C180', 0.5250012874603271, 0.5250012874603271, 0.0015693092467669477), ('C158', 0.5249188542366028, 0.5249188542366028, 0.0015690628412374352), ('C382', 0.524329662322998, 0.524329662322998, 0.0015673016563789882), ('C686', 0.5240523815155029, 0.5240523815155029, 0.0015664728215826812), ('C331', 0.5226954221725464, 0.5226954221725464, 0.0015624166623022157), ('C494', 0.5210068821907043, 0.5210068821907043, 0.0015573693577139568), 

In [63]:
# Predictions
pred = model.predict(test)
print("Predictions: ", pred.head())

deeplearning prediction progress: |██████████████████████████████████████████████| (done) 100%
Predictions:    predict           p0           p1           p2           p3           p4           p5           p6           p7           p8           p9
        8  1.11273e-08  6.22812e-07  9.90168e-07  7.03138e-06  4.21413e-08  2.77153e-06  9.31764e-08  8.1077e-09   0.999987     1.64006e-06
        3  6.05483e-11  3.72786e-08  3.98553e-08  0.999984     4.27197e-10  1.06254e-06  2.81699e-12  1.19649e-06  6.02361e-06  7.65789e-06
        8  0.0812754    0.000508378  0.0128297    0.00772221   0.00496229   0.0985099    0.213177     0.000675486  0.574423     0.00591656
        0  0.997569     2.70662e-08  3.42211e-06  2.442e-07    1.13628e-06  5.87922e-06  0.00241297   2.83724e-07  4.99578e-06  2.52263e-06
        1  7.34495e-11  0.999999     3.47374e-08  1.37428e-08  9.21581e-08  2.21371e-09  1.08854e-08  2.22102e-07  3.51128e-07  1.77772e-08
        5  1.61587e-05  1.69459e-05  2.37344e-05  0.000264944  1.42874e-05  0.878512     0.000117538  1.79895e-05  0.12077      0.000246743
        0  1            2.48509e-13  1.62541e-09  5.19848e-10  3.10565e-11  1.70148e-08  8.90212e-09  8.1043e-09   1.60291e-08  7.39611e-08
        1  1.88692e-10  0.999996     4.79013e-08  2.95513e-08  6.58078e-07  1.48631e-09  5.82922e-09  1.86436e-06  1.04168e-06  1.32208e-07
        5  7.75405e-08  1.10355e-06  7.43423e-07  0.0128555    4.96913e-07  0.986844     9.59526e-06  5.82855e-08  0.000116353  0.000172325
        2  3.28279e-06  0.000205943  0.997005     0.00147778   8.82113e-07  4.34609e-05  1.02301e-05  0.000796683  0.000456332  8.85802e-07
[10 rows x 11 columns]

In [64]:
from h2o.grid.grid_search import H2OGridSearch

# Define hyperparameters for grid search
hidden_opt = [[100, 300, 100], [500, 500, 500]]
l1_opt = [1e-5, 1e-7]
hyper_params = {'hidden': hidden_opt, 'l1': l1_opt}

# Define search criteria
search_criteria = {'strategy': 'RandomDiscrete', 'max_runtime_secs': 900}

# Perform grid search
model_grid = H2OGridSearch(
    model=H2ODeepLearningEstimator(
        distribution='multinomial',
        epochs=5,
        validation_frame=test
    ),
    hyper_params=hyper_params,
    search_criteria=search_criteria
)

model_grid.train(x=x, y=y, training_frame=train)

# Print out all prediction errors of the models
print(model_grid)

deeplearning Grid Build progress: |██████████████████████████████████████████████| (done) 100%
Hyper-Parameter Search Summary: ordered by increasing logloss
    hidden           l1     model_ids                                                               logloss
--  ---------------  -----  ----------------------------------------------------------------------  ---------
    [500, 500, 500]  1e-07  Grid_DeepLearning_py_33_sid_a081_model_python_1717403639876_66_model_1  0.168967

In [65]:
# Print out the Test MSE for all of the models
for model_id in model_grid.model_ids:
    model = h2o.get_model(model_id)
    mse = model.model_performance(valid=True).mse()
    print(f"Model ID: {model_id}, Test set MSE: {mse:.6f}")

Model ID: Grid_DeepLearning_py_33_sid_a081_model_python_1717403639876_66_model_1, Test set MSE: 0.030876

In [67]:
h2o.cluster().shutdown()

H2O session _sid_afbb closed.

# Exercise (Titanic): 45 minutes

[Kaggle](https://www.kaggle.com/competitions/titanic)