# Install Java

In [ ]:
#!apt-get install openjdk-8-jdk
!apt-get install default-jre

In [2]:
!java -version # This command displays Java version.

openjdk version "11.0.22" 2024-01-16
OpenJDK Runtime Environment (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1)
OpenJDK 64-Bit Server VM (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1, mixed mode, sharing)

# Install H2O

In [ ]:
!pip install H2O

In [4]:
import h2o
h2o.init()

Checking whether there is an H2O instance running at http://localhost:54321..... not found.
Attempting to start a local H2O server...
  Java Version: openjdk version "11.0.22" 2024-01-16; OpenJDK Runtime Environment (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1); OpenJDK 64-Bit Server VM (build 11.0.22+7-post-Ubuntu-0ubuntu222.04.1, mixed mode, sharing)
  Starting server from /usr/local/lib/python3.10/dist-packages/h2o/backend/bin/h2o.jar
  Ice root: /tmp/tmph4wpp8bv
  JVM stdout: /tmp/tmph4wpp8bv/h2o_unknownUser_started_from_python.out
  JVM stderr: /tmp/tmph4wpp8bv/h2o_unknownUser_started_from_python.err
  Server is running at http://127.0.0.1:54321
Connecting to H2O server at http://127.0.0.1:54321 ... successful.

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         03 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.2
H2O_cluster_version_age:    20 days
H2O_cluster_name:           H2O_from_python_unknownUser_v7g90w
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.170 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.10.12 final
--------------------------  -----------------------------------------------------------------------------------------

In [5]:
h2o.cluster().show_status() # Check the status and health of the H2O cluster

--------------------------  -----------------------------------------------------------------------------------------
H2O_cluster_uptime:         1 min 17 secs
H2O_cluster_timezone:       Etc/UTC
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.2
H2O_cluster_version_age:    20 days
H2O_cluster_name:           H2O_from_python_unknownUser_v7g90w
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    3.170 Gb
H2O_cluster_total_cores:    2
H2O_cluster_allowed_cores:  2
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://127.0.0.1:54321
H2O_connection_proxy:       {"http": null, "https": null, "colab_language_server": "/usr/colab/bin/language_service"}
H2O_internal_security:      False
Python_version:             3.10.12 final
--------------------------  -----------------------------------------------------------------------------------------

# Tunel to localhost

In [6]:
!npm install -g localtunnel

/tools/node/bin/lt -> /tools/node/lib/node_modules/localtunnel/bin/lt.js
+ localtunnel@2.0.2
added 22 packages from 22 contributors in 2.261s

In [7]:
get_ipython().system_raw('lt --port 54321 >> url.txt &')

In [8]:
!cat url.txt

your url is: https://violet-beds-make.loca.lt

In [9]:
!curl https://loca.lt/mytunnelpassword

34.86.55.107

# Data Preparation and simple statistics
Although it may seem like you are manipulating the data in Python, once the
data has been passed to H2O, all data munging occurs in the H2O
instance. You are limited by the total amount of memory allocated to the H2O
instance, not by Python's ability to handle data.

In [ ]:
airlinesURL = 'https://s3.amazonaws.com/h2o-airlines-unpacked/allyears2k.csv' # File path
# The U.S. Department of Transportation's (DOT) Bureau of Transportation Statistics (BTS)
# tracks the on-time performance of domestic flights operated by large air carriers.

airlines_hex = h2o.import_file(airlinesURL, destination_frame = 'airlines_hex')
airlines_hex.head()

In [ ]:
# Summary statistics
airlines_hex.describe()

In [12]:
# Quantiles of the ArrDelay column
quantiles = airlines_hex['ArrDelay'].quantile(prob = [0.25, 0.5, 0.75, 1.0])
print(quantiles)

  Probs    ArrDelayQuantiles
   0.25                   -6
   0.5                     2
   0.75                   14
   1                     475
[4 rows x 2 columns]

In [13]:
# Histogram of the ArrDelay column
airlines_hex['ArrDelay'].hist()

    breaks    counts    mids_true      mids    widths
----------  --------  -----------  --------  --------
-31.3529         nan        nan    nan       nan
  0.294118       173        -31.5  -15.5294   31.6471
 31.9412       19364        -15.5   16.1176   31.6471
 63.5882       18089          0.5   47.7647   31.6471
 95.2353        3163         16     79.4118   31.6471
126.882         1067         32    111.059    31.6471
158.529          444         48    142.706    31.6471
190.176          221         63.5  174.353    31.6471
221.824          116         79.5  206        31.6471
253.471           60         95.5  237.647    31.6471
[17 rows x 5 columns]

In [14]:
# Check if any column is a factor
any(airlines_hex.type(col) == 'enum' for col in airlines_hex.names)

True

In [15]:
# Group by 'Origin' and calculate the number of rows, removing NA values
airlines_hex.group_by('Origin').count(na='rm').get_frame()

Origin      nrow
--------  ------
ABE           59
ABQ          876
ACY           31
ALB           75
AMA           11
ANC            1
ATL          754
AUS          835
AVP          154
BDL          141
[132 rows x 2 columns]

In [16]:
# Group by 'Month' and calculate the number of rows, removing NA values
airlines_hex.group_by('Month').count(na='rm').get_frame()

  Month    nrow
-------  ------
      1   41979
     10    1999
[2 rows x 2 columns]

In [17]:
# Group by 'Month' and calculate the number of cancellations, removing NA values
cancellations_by_month = airlines_hex.group_by('Month').sum('Cancelled', na='rm').get_frame()
print(cancellations_by_month)

# Group by 'Month' and calculate the number of flights, removing NA values
flights_by_month = airlines_hex.group_by('Month').count(na='rm').get_frame()
print(flights_by_month)

# Calculate cancellation rate
cancellation_rate = cancellations_by_month['sum_Cancelled'] / flights_by_month['nrow']
print(cancellation_rate)

# Combine month and cancellation rate into a single table
rates_table = flights_by_month.cbind(cancellation_rate)
rates_table.set_name(2, 'Cancellation_Rate')
print(rates_table)

  Month    sum_Cancelled
      1             1067
     10               19
[2 rows x 2 columns]

  Month    nrow
      1   41979
     10    1999
[2 rows x 2 columns]

  sum_Cancelled
     0.0254175
     0.00950475
[2 rows x 1 column]

  Month    nrow    Cancellation_Rate
      1   41979           0.0254175
     10    1999           0.00950475
[2 rows x 3 columns]

In [18]:
# Generate a frequency table for the 'Cancelled' column
airlines_hex['Cancelled'].table()

# Because H2O can handle larger datasets, it is possible to generate tables that are larger than Python's capacity, so use caution when executing this command.

  Cancelled    Count
-----------  -------
          0    42892
          1     1086
[2 rows x 2 columns]

# Data Manipulation

In [19]:
from sklearn.datasets import load_iris
import pandas as pd

# Load iris dataset from sklearn and convert to pandas DataFrame
iris = load_iris()
iris_df = pd.DataFrame(data = iris.data, columns = iris.feature_names)
iris_df['target'] = iris.target

# Convert pandas DataFrame to h2o Frame
iris_hex = h2o.H2OFrame(iris_df, destination_frame = 'iris_hex')
# Ensure the target column is treated as a categorical factor
iris_hex['target'] = iris_hex['target'].asfactor()

# List all objects in h2o
h2o.ls()

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

/usr/local/lib/python3.10/dist-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install datatable (for Python 3.9 or lower), or polars and pyarrow (for Python 3.10 or above) and activate it using:

with h2o.utils.threading.local_context(polars_enabled=True, datatable_enabled=True):
    pandas_df = h2o_df.as_data_frame()

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"

               key
0     airlines_hex
1         iris_hex
2   py_10_sid_a081
3   py_12_sid_a081
4   py_14_sid_a081
5   py_16_sid_a081
6   py_17_sid_a081
7   py_18_sid_a081
8   py_19_sid_a081
9    py_1_sid_a081
10   py_2_sid_a081
11   py_3_sid_a081
12   py_4_sid_a081
13   py_5_sid_a081

In [20]:
# Splitting Frames
# h2o.splitFrame() does not give an exact split. H2O is designed
# to be efficient on big data using a probabilistic splitting method rather than an
# exact split. On small datasets, the sizes of the resulting splits will deviate from
# the expected value more than on big data, where they will be very close to
# exact.
iris_split = iris_hex.split_frame(ratios=[0.75], seed = 1234)

# Creates training set from 1st data set in split
iris_train = iris_split[0]

# Creates testing set from 2nd data set in split
iris_test = iris_split[1]

# List all objects in h2o
h2o.ls()

/usr/local/lib/python3.10/dist-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install datatable (for Python 3.9 or lower), or polars and pyarrow (for Python 3.10 or above) and activate it using:

with h2o.utils.threading.local_context(polars_enabled=True, datatable_enabled=True):
    pandas_df = h2o_df.as_data_frame()

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"

               key
0     airlines_hex
1         iris_hex
2   py_10_sid_a081
3   py_12_sid_a081
4   py_14_sid_a081
5   py_16_sid_a081
6   py_17_sid_a081
7   py_18_sid_a081
8   py_19_sid_a081
9    py_1_sid_a081
10  py_21_sid_a081
11  py_23_sid_a081
12  py_24_sid_a081
13   py_2_sid_a081
14   py_3_sid_a081
15   py_4_sid_a081
16   py_5_sid_a081

In [21]:
# Define the function
def simple_fun(x):
    return 2 * x + 5

# Apply the function to the 'Sepal.Length' column
calculated = simple_fun(iris_hex['sepal length (cm)'])

# Combine the original 'Sepal.Length' column with the calculated values
combined = iris_hex['sepal length (cm)'].cbind(calculated)

# Display the combined result
h2o.as_list(combined)

/usr/local/lib/python3.10/dist-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install datatable (for Python 3.9 or lower), or polars and pyarrow (for Python 3.10 or above) and activate it using:

with h2o.utils.threading.local_context(polars_enabled=True, datatable_enabled=True):
    pandas_df = h2o_df.as_data_frame()

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"

     sepal length (cm)  sepal length (cm)0
0                  5.1                15.2
1                  4.9                14.8
2                  4.7                14.4
3                  4.6                14.2
4                  5.0                15.0
..                 ...                 ...
145                6.7                18.4
146                6.3                17.6
147                6.5                18.0
148                6.2                17.4
149                5.9                16.8

[150 rows x 2 columns]

# Running Models

## Classification (1)

In [22]:
from h2o.estimators import H2OGradientBoostingEstimator

In [ ]:
# Train a GBM model
iris_gbm = H2OGradientBoostingEstimator()
iris_gbm.train(y = 'target',
               x = iris_df.columns[:-1].tolist(),
               training_frame = iris_train)

In [24]:
# Predict on the test set
predictions = iris_gbm.predict(iris_test)
print(predictions)

gbm prediction progress: |███████████████████████████████████████████████████████| (done) 100%
  predict        p0           p1           p2
        0  0.99861   0.000700155  0.000690257
        0  0.99861   0.000700194  0.0006903
        0  0.991104  0.0084341    0.00046142
        0  0.998743  0.000772911  0.00048404
        0  0.997291  0.0023294    0.000379907
        0  0.998743  0.000772674  0.000483892
        0  0.99774   0.00186488   0.000395214
        0  0.998743  0.000772674  0.000483892
        0  0.998397  0.00115858   0.000444536
        0  0.998635  0.000729049  0.00063585
[33 rows x 4 columns]

In [25]:
# Generate the performance metrics for the test set
performance = iris_gbm.model_performance(iris_test)

In [26]:
performance.confusion_matrix()

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class
0    1    2    Error      Rate
---  ---  ---  ---------  ------
15   0    0    0          0 / 15
0    11   1    0.0833333  1 / 12
0    1    5    0.166667   1 / 6
15   12   6    0.0606061  2 / 33

In [29]:
performance.hit_ratio_table()

Top-3 Hit Ratios:
k    hit_ratio
---  -----------
1    0.939394
2    1
3    1

## Classification (2)

In [30]:
from h2o.estimators import H2OGeneralizedLinearEstimator

# Import the prostate dataset
prostate_hex = h2o.import_file('https://raw.github.com/h2oai/h2o/master/smalldata/logreg/prostate.csv',
                               destination_frame='prostate_hex')

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

In [ ]:
# Train a GLM model for logistic classification
prostate_glm = H2OGeneralizedLinearEstimator(family = 'binomial', nfolds = 10)
prostate_glm.train(y='CAPSULE', x=['AGE', 'RACE', 'PSA', 'DCAPS'], training_frame = prostate_hex)

In [ ]:
# Get cross-validation metrics
prostate_glm.cross_validation_metrics_summary().as_data_frame()

In [ ]:
# Predict on the same dataset
prostate_glm.predict(prostate_hex)

In [34]:
# Calculate AUC
auc = prostate_glm.auc()
print(f'AUC: {auc}')

AUC: 0.7176009904696092

In [ ]:
# Generate the confusion matrix
confusion_matrix = prostate_glm.confusion_matrix()
print(confusion_matrix)

In [ ]:
# Get performance metrics on the training data
performance = prostate_glm.model_performance(prostate_hex)
print(performance)

## Regression

The Loblolly data frame has 84 rows and 3 columns of records of the growth of Loblolly pine trees.

Kung, F. H. (1986), Fitting logistic growth curve with predetermined carrying capacity, in Proceedings of the Statistical Computing Section, American Statistical Association, 340–343.

Pinheiro, J. C. and Bates, D. M. (2000) Mixed-effects Models in S and S-PLUS, Springer.

In [ ]:
# Import the Loblolly dataset from the CSV file
loblolly_hex = h2o.import_file('loblolly.csv', destination_frame = 'Loblolly_hex')
loblolly_hex

In [ ]:
# Train a GLM model for regression
loblolly_glm = H2OGeneralizedLinearEstimator(nfolds = 10)
loblolly_glm.train(y='height', x=['age'], training_frame = loblolly_hex)

In [ ]:
# Predict using the GLM model
glm_predict = loblolly_glm.predict(loblolly_hex)
print(glm_predict)

In [40]:
from h2o.automl import H2OAutoML

In [ ]:
# Train an AutoML model
loblolly_automl = H2OAutoML(max_runtime_secs = 60)
loblolly_automl.train(y='height', x=['age'], training_frame=loblolly_hex)

In [ ]:
loblolly_automl.get_leaderboard()

In [ ]:
# Get the leader model from AutoML
leader_model = loblolly_automl.leader
print(leader_model)

# Predict using the AutoML leader model
automl_predict = leader_model.predict(loblolly_hex)
print(automl_predict)

## Clustering

In [44]:
from h2o.estimators import H2OKMeansEstimator

In [ ]:
iris_kmeans = H2OKMeansEstimator(k = 3)
iris_kmeans.train(x = list(range(0, 4)),
                  training_frame = iris_hex)

In [ ]:
# Print model details
print(iris_kmeans)

In [ ]:
# Show cluster centers
print("Cluster Centers: ", iris_kmeans.centers())

In [ ]:
# Show clustering metrics
print("Clustering Metrics: ", iris_kmeans._model_json['output']['training_metrics'])

## PCA

In [49]:
from h2o.estimators import H2OPrincipalComponentAnalysisEstimator

In [ ]:
iris_pca_data = iris_hex[:, :-1]

# Train a PCA model
iris_pca = H2OPrincipalComponentAnalysisEstimator(k=2, transform='NORMALIZE')
iris_pca.train(training_frame=iris_pca_data)

In [ ]:
# Print model details
print(iris_pca)

In [ ]:
# Show the principal components
print("Principal Components: ", iris_pca._model_json['output']['importance'])

In [53]:
# Get the principal component projections
pca_projections = iris_pca.predict(iris_pca_data)
print(pca_projections)

pca prediction progress: |███████████████████████████████████████████████████████| (done) 100%
     PC1         PC2
0.630703   0.107578
0.622905  -0.10426
0.66952   -0.0514171
0.654153  -0.102885
0.648788   0.133488
0.535273   0.289616
0.656538   0.0107245
0.62578    0.0571335
0.675644  -0.200703
0.645645  -0.067208
[150 rows x 2 columns]

# Case Study (MNIST)

In [54]:
# URLs to the train and test datasets
train_file = 'https://h2o-public-test-data.s3.amazonaws.com/bigdata/laptop/mnist/train.csv.gz'
test_file = 'https://h2o-public-test-data.s3.amazonaws.com/bigdata/laptop/mnist/test.csv.gz'

# Import the datasets
train = h2o.import_file(train_file)
test = h2o.import_file(test_file)

# Display a brief summary of the data
train.summary()
test.summary()

Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%

<ipython-input-54-e73e24c90c96>:10: H2ODeprecationWarning: ``summary()`` is deprecated, please use ``show_summary()`` or ``get_summary()`` instead
  train.summary()

         C1     C2     C3     C4     C5     C6     C7     C8     C9     C10    C11    C12    C13                 C14                   C15                C16                  C17    C18    C19    C20    C21    C22    C23    C24    C25    C26    C27    C28    C29    C30    C31    C32    C33                    C34                    C35                   C36                   C37                  C38                C39                  C40                  C41                  C42                  C43                  C44                C45                  C46                C47                  C48                  C49                   C50                   C51                   C52                   C53    C54    C55    C56    C57    C58    C59                    C60                  C61                 C62                   C63                 C64                C65                 C66                 C67                 C68                 C69                 C70                 C71                 C72                 C73                 C74                C75                 C76                 C77                 C78                 C79                 C80                  C81                  C82                   C83    C84    C85    C86    C87                    C88                 C89                   C90                  C91                  C92                C93                 C94                 C95                 C96                 C97                 C98                 C99                 C100                C101                C102               C103               C104               C105                C106                C107                C108                C109                 C110                  C111              C112    C113    C114                   C115                  C116                C117                 C118                C119                C120                C121                C122               C123                C124                C125               C126               C127               C128               C129               C130               C131               C132               C133                C134               C135                C136               C137                C138               C139               C140                  C141    C142    C143                  C144               C145                C146                C147                C148               C149               C150                C151                C152               C153                C154                C155                C156                C157                C158                C159              C160                C161                C162                C163               C164                C165                C166                C167                 C168                C169    C170                    C171               C172                 C173                C174               C175               C176               C177                C178               C179                C180                C181                C182                C183                C184                C185                C186                C187                C188                C189               C190               C191               C192                C193                C194                C195                C196                C197                   C198                  C199                 C200                C201               C202               C203                C204                C205              C206               C207                C208                C209                C210                C211                C212                C213                C214                C215                C216               C217                C218               C219                C220                C221               C222                C223               C224                 C225                  C226                 C227                 C228                C229                C230                C231                C232                C233               C234                C235                C236                C237                C238                C239                C240                C241                C242                C243                C244                C245                C246               C247                C248                C249                C250                C251                C252                  C253                  C254                 C255                C256                C257                C258               C259                C260               C261                C262                C263                C264                C265                C266                C267                C268                C269                C270                C271                C272                C273                C274                C275                C276                C277                C278                C279                 C280                  C281                  C282                 C283                C284                C285                C286               C287                C288               C289               C290                C291                C292                C293                C294               C295                C296                C297               C298                C299                C300                C301                C302                C303                C304                C305                C306                C307                 C308                  C309                  C310               C311                 C312                C313                C314               C315               C316                C317               C318                C319                C320                C321                C322                C323               C324                C325                C326                C327                C328                C329               C330                C331                C332                C333                C334                C335               C336                  C337                C338                 C339                 C340                C341                C342               C343                C344               C345                C346                C347                C348               C349                C350                C351                C352                C353                C354                C355                C356                C357               C358               C359                C360                C361                C362               C363                 C364                  C365                   C366                C367                 C368                C369                C370                C371                C372               C373               C374                C375                C376                C377                C378                C379                C380                C381                C382                C383                C384                C385               C386                C387                C388                C389                C390               C391                 C392                  C393                   C394               C395                 C396                 C397                C398                C399               C400                C401               C402                C403                C404                C405                C406                C407                C408                C409                C410                C411                C412               C413               C414               C415                C416                C417               C418                C419                C420                   C421                   C422                   C423               C424                C425               C426                C427                C428               C429                C430               C431               C432                C433                C434                C435                C436                C437                C438                C439                C440                C441               C442               C443                C444                C445               C446                C447                 C448                  C449                   C450                  C451                 C452                C453                C454                C455               C456                C457               C458               C459               C460                C461                C462                C463                C464                C465                C466                C467               C468                C469               C470               C471               C472                C473               C474                C475               C476                C477    C478                   C479               C480                C481               C482                C483               C484                C485               C486                C487                C488                C489                C490                C491                C492                C493                C494                C495               C496              C497               C498               C499                C500                C501                C502                C503                 C504                  C505                C506                  C507               C508               C509               C510                C511                C512                C513                C514                C515                C516                C517                C518                C519                C520                C521                C522                C523                C524                C525               C526               C527                C528               C529                C530                C531                 C532                  C533                 C534                  C535                 C536                C537                C538                C539                C540               C541               C542                C543               C544                C545                C546                C547                C548                C549                C550                C551                C552                C553               C554                C555                C556                C557                C558                C559               C560                  C561    C562                  C563               C564                C565               C566                C567               C568               C569                C570                C571                C572                C573                C574                C575                C576                C577                C578                C579                C580               C581               C582               C583                C584                C585                C586                C587                 C588                   C589                   C590                C591                 C592                C593                C594                C595               C596               C597                C598                C599                C600                C601                C602                C603                C604                C605                C606                C607               C608               C609               C610                C611                C612                C613                C614                C615               C616                 C617                   C618                   C619                 C620                C621                C622                C623               C624               C625                C626                C627                C628                C629               C630                C631               C632                C633                C634               C635               C636               C637                C638               C639                C640                C641                C642                 C643                  C644                C645    C646    C647                 C648                C649                C650                C651                C652                C653               C654               C655               C656                C657                C658                C659                C660                C661               C662               C663                C664                C665               C666                C667                C668                C669                C670                  C671                  C672    C673    C674    C675                C676               C677                C678                C679                C680               C681               C682               C683               C684               C685               C686               C687                C688               C689                C690                C691                C692                C693                C694                C695                C696                 C697                 C698                  C699                   C700    C701    C702    C703                   C704                  C705                 C706              C707                C708                C709                C710               C711                C712                C713                C714               C715                C716                C717                C718               C719                C720                C721                C722                C723                C724                 C725                  C726                   C727                   C728    C729    C730    C731    C732                   C733               C734                 C735                C736                C737                C738                C739                C740               C741               C742                C743                C744                C745                C746                C747                C748                C749                C750               C751                 C752                  C753                   C754                   C755    C756    C757    C758    C759    C760    C761                  C762                  C763                  C764                C765                 C766                 C767                C768                 C769                C770                C771                C772                C773                 C774                C775                 C776                 C777                 C778                  C779                  C780                 C781    C782    C783    C784    C785

         C1     C2     C3     C4     C5     C6     C7     C8     C9     C10    C11    C12    C13    C14    C15    C16    C17    C18    C19    C20    C21    C22    C23    C24    C25    C26    C27    C28    C29    C30    C31    C32    C33    C34     C35     C36     C37                 C38                 C39                 C40                C41                C42                C43                C44                C45                C46                 C47                C48                  C49                 C50    C51    C52    C53    C54    C55    C56    C57    C58    C59    C60    C61    C62                C63                C64                C65                C66                C67                 C68                 C69                 C70                 C71                 C72                 C73                C74                 C75                C76                 C77                C78                C79                C80                C81     C82    C83    C84    C85    C86    C87    C88    C89                 C90                 C91                 C92                C93                 C94                 C95                 C96                 C97                 C98                 C99                C100                C101               C102               C103               C104               C105               C106                C107                C108              C109                C110              C111    C112    C113    C114    C115    C116                  C117               C118               C119                C120               C121                C122               C123                C124                C125              C126                C127               C128               C129               C130               C131               C132                C133                C134               C135                C136               C137                C138               C139               C140    C141    C142                 C143                   C144               C145               C146                C147                C148                C149                C150               C151               C152               C153               C154                C155                C156                C157                C158                C159               C160               C161               C162                C163                C164               C165               C166                C167              C168    C169    C170    C171                 C172               C173               C174               C175                C176               C177               C178               C179               C180                C181                C182                C183                C184                C185                C186                C187                C188                C189               C190                C191                C192                C193               C194               C195              C196                C197    C198                C199                C200               C201                C202              C203                C204                C205               C206               C207                C208                C209                C210                C211                C212              C213                C214                C215                C216                C217               C218                C219                C220                C221                C222                C223               C224                C225    C226               C227               C228               C229               C230                C231              C232                C233               C234                C235                C236                C237                C238                C239                C240                C241                C242                C243                C244                C245                C246             C247                C248                C249                C250                C251                C252                 C253                C254               C255               C256               C257               C258                C259               C260                C261               C262                C263                C264                C265                C266                C267                C268                C269                C270                C271                C272                C273                C274                C275                C276                C277                C278                C279               C280                C281                  C282               C283               C284              C285                C286               C287                C288                C289               C290                C291                C292                C293                C294                C295                C296                C297               C298                C299                C300                C301                C302                C303               C304                C305                C306                C307               C308                C309    C310               C311               C312                C313                C314                C315                C316               C317                C318                C319                C320               C321                C322               C323                C324                C325                C326                C327                C328                C329              C330               C331               C332               C333                C334                C335                 C336                C337    C338                C339               C340                C341                C342                C343                C344                C345                C346                C347                C348                C349                C350               C351                C352                C353                C354                C355                C356                C357                C358               C359               C360                C361                C362               C363                C364    C365    C366                  C367                C368               C369                C370                C371               C372               C373                C374                C375                C376                C377                C378               C379                C380                C381                C382                C383                C384                C385               C386               C387                C388               C389                C390                C391                C392    C393    C394    C395                C396               C397                C398                C399               C400               C401                C402                C403                C404                C405                C406                C407                C408                C409                C410                C411                C412                C413                C414               C415                C416               C417                C418                C419                C420    C421    C422    C423                C424               C425               C426                C427               C428               C429                C430               C431                C432                C433                C434                C435                C436                C437                C438                C439                C440                C441               C442               C443               C444                C445                C446                C447               C448                C449    C450                  C451               C452               C453               C454                C455               C456                C457               C458                C459                C460                C461                C462                C463                C464                C465                C466                C467               C468               C469                C470                C471               C472               C473                C474                C475                C476                C477    C478    C479                C480                C481                C482               C483                C484               C485               C486                C487               C488               C489               C490                C491                C492               C493               C494                C495               C496                C497               C498               C499                C500                C501                C502                C503               C504                C505    C506    C507               C508                C509               C510                C511               C512               C513                C514                C515                C516                C517                C518                C519                C520                C521                C522                C523                C524                C525               C526                C527                C528                C529              C530                C531               C532    C533    C534                  C535                 C536                C537               C538               C539                C540               C541               C542                C543                C544                C545                C546                C547                C548                C549                C550                C551                C552               C553               C554               C555                C556               C557               C558                C559                C560    C561    C562    C563               C564               C565                C566                C567                C568               C569                C570                C571                C572                C573                C574                C575                C576                C577                C578                C579                C580               C581               C582                C583               C584                C585                C586                C587               C588    C589    C590    C591               C592                C593                C594                C595               C596               C597                C598                C599                C600                C601                C602                C603                C604                C605                C606                C607                C608                C609               C610               C611                C612                C613                C614               C615               C616    C617    C618    C619                C620                C621                C622                C623                C624               C625              C626                C627                C628                C629                C630                C631                C632                C633                C634                C635               C636               C637                C638              C639                C640               C641                C642               C643                C644    C645    C646                 C647                C648               C649               C650                C651               C652                C653               C654                C655                C656                C657                C658                C659               C660                C661               C662               C663                C664                C665                C666               C667                C668                C669               C670                C671    C672    C673    C674    C675    C676                C677               C678                C679                C680              C681                C682               C683               C684               C685               C686               C687                C688               C689               C690                C691                C692              C693                C694                C695               C696                C697                C698    C699    C700    C701    C702    C703    C704                 C705                C706               C707               C708               C709               C710             C711                C712               C713                C714               C715               C716                C717                C718                C719               C720                C721               C722                C723               C724                C725                  C726                C727    C728    C729    C730    C731    C732    C733                 C734              C735              C736                C737                C738                C739                C740                C741               C742               C743               C744               C745                C746                C747                C748              C749                C750               C751               C752              C753                   C754    C755    C756    C757    C758    C759    C760    C761    C762    C763                 C764               C765               C766               C767               C768               C769               C770               C771                C772                C773               C774               C775               C776               C777                C778                  C779    C780    C781    C782    C783    C784    C785

In [55]:
# Specify the response and predictor columns
y = 'C785'
x = list(set(train.names) - set([y]))

# Encode the response column as categorical for classification
train[y] = train[y].asfactor()
test[y] = test[y].asfactor()

In [ ]:
from h2o.estimators import H2ODeepLearningEstimator
# The example below illustrates the relative simplicity underlying most H2O Deep Learning model parameter
# configurations, as a result of the default settings. Rectified linear activation is popular
# with image processing and has performed well on the MNIST database previously and dropout has been
# known to enhance performance on this dataset as well, so we train our model accordingly.

# Train a Deep Learning model and validate on a test set.

# Train the deep learning model
model = H2ODeepLearningEstimator(
    distribution='multinomial',
    activation='RectifierWithDropout',
    hidden=[200, 200, 200], # 784-200-200-200-10
    input_dropout_ratio=0.2, # 784 * 200 + 200 + 200 * 200 + 200 + 200 * 200 +200 + 200 * 10 + 10 =  239 410 parameters
    l1=1e-5,
    epochs=10,
    variable_importances=True
)

model.train(x=x, y=y, training_frame=train, validation_frame=test)

In [57]:
# View the specified parameters
print("Model parameters: ", model.params)

Model parameters:  {'model_id': {'default': None, 'actual': {'__meta': {'schema_version': 3, 'schema_name': 'ModelKeyV3', 'schema_type': 'Key<Model>'}, 'name': 'DeepLearning_model_python_1717403639876_65', 'type': 'Key<Model>', 'URL': '/3/Models/DeepLearning_model_python_1717403639876_65'}, 'input': None}, 'training_frame': {'default': None, 'actual': {'__meta': {'schema_version': 3, 'schema_name': 'FrameKeyV3', 'schema_type': 'Key<Frame>'}, 'name': 'py_33_sid_a081', 'type': 'Key<Frame>', 'URL': '/3/Frames/py_33_sid_a081'}, 'input': {'__meta': {'schema_version': 3, 'schema_name': 'FrameKeyV3', 'schema_type': 'Key<Frame>'}, 'name': 'py_33_sid_a081', 'type': 'Key<Frame>', 'URL': '/3/Frames/py_33_sid_a081'}}, 'validation_frame': {'default': None, 'actual': {'__meta': {'schema_version': 3, 'schema_name': 'FrameKeyV3', 'schema_type': 'Key<Frame>'}, 'name': 'py_34_sid_a081', 'type': 'Key<Frame>', 'URL': '/3/Frames/py_34_sid_a081'}, 'input': {'__meta': {'schema_version': 3, 'schema_name': 'FrameKeyV3', 'schema_type': 'Key<Frame>'}, 'name': 'py_34_sid_a081', 'type': 'Key<Frame>', 'URL': '/3/Frames/py_34_sid_a081'}}, 'nfolds': {'default': 0, 'actual': 0, 'input': 0}, 'keep_cross_validation_models': {'default': True, 'actual': True, 'input': True}, 'keep_cross_validation_predictions': {'default': False, 'actual': False, 'input': False}, 'keep_cross_validation_fold_assignment': {'default': False, 'actual': False, 'input': False}, 'fold_assignment': {'default': 'AUTO', 'actual': None, 'input': 'AUTO'}, 'fold_column': {'default': None, 'actual': None, 'input': None}, 'response_column': {'default': None, 'actual': {'__meta': {'schema_version': 3, 'schema_name': 'ColSpecifierV3', 'schema_type': 'VecSpecifier'}, 'column_name': 'C785', 'is_member_of_frames': None}, 'input': {'__meta': {'schema_version': 3, 'schema_name': 'ColSpecifierV3', 'schema_type': 'VecSpecifier'}, 'column_name': 'C785', 'is_member_of_frames': None}}, 'ignored_columns': {'default': None, 'actual': None, 'input': None}, 'ignore_const_cols': {'default': True, 'actual': True, 'input': True}, 'score_each_iteration': {'default': False, 'actual': False, 'input': False}, 'weights_column': {'default': None, 'actual': None, 'input': None}, 'offset_column': {'default': None, 'actual': None, 'input': None}, 'balance_classes': {'default': False, 'actual': False, 'input': False}, 'class_sampling_factors': {'default': None, 'actual': None, 'input': None}, 'max_after_balance_size': {'default': 5.0, 'actual': 5.0, 'input': 5.0}, 'max_confusion_matrix_size': {'default': 20, 'actual': 20, 'input': 20}, 'checkpoint': {'default': None, 'actual': None, 'input': None}, 'pretrained_autoencoder': {'default': None, 'actual': None, 'input': None}, 'overwrite_with_best_model': {'default': True, 'actual': True, 'input': True}, 'use_all_factor_levels': {'default': True, 'actual': True, 'input': True}, 'standardize': {'default': True, 'actual': True, 'input': True}, 'activation': {'default': 'Rectifier', 'actual': 'RectifierWithDropout', 'input': 'RectifierWithDropout'}, 'hidden': {'default': [200, 200], 'actual': [200, 200, 200], 'input': [200, 200, 200]}, 'epochs': {'default': 10.0, 'actual': 10.0, 'input': 10.0}, 'train_samples_per_iteration': {'default': -2, 'actual': -2, 'input': -2}, 'target_ratio_comm_to_comp': {'default': 0.05, 'actual': 0.05, 'input': 0.05}, 'seed': {'default': -1, 'actual': 5419331722423643436, 'input': -1}, 'adaptive_rate': {'default': True, 'actual': True, 'input': True}, 'rho': {'default': 0.99, 'actual': 0.99, 'input': 0.99}, 'epsilon': {'default': 1e-08, 'actual': 1e-08, 'input': 1e-08}, 'rate': {'default': 0.005, 'actual': 0.005, 'input': 0.005}, 'rate_annealing': {'default': 1e-06, 'actual': 1e-06, 'input': 1e-06}, 'rate_decay': {'default': 1.0, 'actual': 1.0, 'input': 1.0}, 'momentum_start': {'default': 0.0, 'actual': 0.0, 'input': 0.0}, 'momentum_ramp': {'default': 1000000.0, 'actual': 1000000.0, 'input': 1000000.0}, 'momentum_stable': {'default': 0.0, 'actual': 0.0, 'input': 0.0}, 'nesterov_accelerated_gradient': {'default': True, 'actual': True, 'input': True}, 'input_dropout_ratio': {'default': 0.0, 'actual': 0.2, 'input': 0.2}, 'hidden_dropout_ratios': {'default': None, 'actual': None, 'input': None}, 'l1': {'default': 0.0, 'actual': 1e-05, 'input': 1e-05}, 'l2': {'default': 0.0, 'actual': 0.0, 'input': 0.0}, 'max_w2': {'default': 3.4028235e+38, 'actual': 3.4028235e+38, 'input': 3.4028235e+38}, 'initial_weight_distribution': {'default': 'UniformAdaptive', 'actual': 'UniformAdaptive', 'input': 'UniformAdaptive'}, 'initial_weight_scale': {'default': 1.0, 'actual': 1.0, 'input': 1.0}, 'initial_weights': {'default': None, 'actual': None, 'input': None}, 'initial_biases': {'default': None, 'actual': None, 'input': None}, 'loss': {'default': 'Automatic', 'actual': 'Automatic', 'input': 'Automatic'}, 'distribution': {'default': 'AUTO', 'actual': 'multinomial', 'input': 'multinomial'}, 'quantile_alpha': {'default': 0.5, 'actual': 0.5, 'input': 0.5}, 'tweedie_power': {'default': 1.5, 'actual': 1.5, 'input': 1.5}, 'huber_alpha': {'default': 0.9, 'actual': 0.9, 'input': 0.9}, 'score_interval': {'default': 5.0, 'actual': 5.0, 'input': 5.0}, 'score_training_samples': {'default': 10000, 'actual': 10000, 'input': 10000}, 'score_validation_samples': {'default': 0, 'actual': 0, 'input': 0}, 'score_duty_cycle': {'default': 0.1, 'actual': 0.1, 'input': 0.1}, 'classification_stop': {'default': 0.0, 'actual': 0.0, 'input': 0.0}, 'regression_stop': {'default': 1e-06, 'actual': 1e-06, 'input': 1e-06}, 'stopping_rounds': {'default': 5, 'actual': 5, 'input': 5}, 'stopping_metric': {'default': 'AUTO', 'actual': 'logloss', 'input': 'AUTO'}, 'stopping_tolerance': {'default': 0.0, 'actual': 0.0, 'input': 0.0}, 'max_runtime_secs': {'default': 0.0, 'actual': 0.0, 'input': 0.0}, 'score_validation_sampling': {'default': 'Uniform', 'actual': 'Uniform', 'input': 'Uniform'}, 'diagnostics': {'default': True, 'actual': True, 'input': True}, 'fast_mode': {'default': True, 'actual': True, 'input': True}, 'force_load_balance': {'default': True, 'actual': True, 'input': True}, 'variable_importances': {'default': True, 'actual': True, 'input': True}, 'replicate_training_data': {'default': True, 'actual': True, 'input': True}, 'single_node_mode': {'default': False, 'actual': False, 'input': False}, 'shuffle_training_data': {'default': False, 'actual': False, 'input': False}, 'missing_values_handling': {'default': 'MeanImputation', 'actual': 'MeanImputation', 'input': 'MeanImputation'}, 'quiet_mode': {'default': False, 'actual': False, 'input': False}, 'autoencoder': {'default': False, 'actual': False, 'input': False}, 'sparse': {'default': False, 'actual': False, 'input': False}, 'col_major': {'default': False, 'actual': False, 'input': False}, 'average_activation': {'default': 0.0, 'actual': 0.0, 'input': 0.0}, 'sparsity_beta': {'default': 0.0, 'actual': 0.0, 'input': 0.0}, 'max_categorical_features': {'default': 2147483647, 'actual': 2147483647, 'input': 2147483647}, 'reproducible': {'default': False, 'actual': False, 'input': False}, 'export_weights_and_biases': {'default': False, 'actual': False, 'input': False}, 'mini_batch_size': {'default': 1, 'actual': 1, 'input': 1}, 'categorical_encoding': {'default': 'AUTO', 'actual': 'OneHotInternal', 'input': 'AUTO'}, 'elastic_averaging': {'default': False, 'actual': False, 'input': False}, 'elastic_averaging_moving_rate': {'default': 0.9, 'actual': 0.9, 'input': 0.9}, 'elastic_averaging_regularization': {'default': 0.001, 'actual': 0.001, 'input': 0.001}, 'export_checkpoints_dir': {'default': None, 'actual': None, 'input': None}, 'auc_type': {'default': 'AUTO', 'actual': 'AUTO', 'input': 'AUTO'}, 'custom_metric_func': {'default': None, 'actual': None, 'input': None}, 'gainslift_bins': {'default': -1, 'actual': -1, 'input': -1}}

In [ ]:
# Display all performance metrics
print("Model performance: ", model)

In [59]:
# Training set metrics
train_perf = model.model_performance(train)
print("Training performance: ", train_perf)

Training performance:  ModelMetricsMultinomial: deeplearning
** Reported on test data. **

MSE: 0.024053370982466692
RMSE: 0.15509149229556948
LogLoss: 0.0911854682473896
Mean Per-Class Error: 0.028490943953264986
AUC table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).
AUCPR table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class
0     1     2     3     4     5     6     7     8     9     Error      Rate
----  ----  ----  ----  ----  ----  ----  ----  ----  ----  ---------  --------------
5844  1     19    6     3     8     21    2     13    6     0.0133378  79 / 5,923
1     6640  52    9     5     3     1     14    15    2     0.015129   102 / 6,742
13    7     5812  26    24    3     18    26    25    4     0.0245049  146 / 5,958
1     1     87    5870  4     69    2     42    39    16    0.0425705  261 / 6,131
3     11    25    0     5678  3     25    8     13    76    0.0280726  164 / 5,842
14    4     16    74    12    5214  40    5     26    16    0.0381848  207 / 5,421
24    7     19    1     13    34    5812  0     8     0     0.0179115  106 / 5,918
7     17    37    5     31    1     0     6126  5     36    0.0221868  139 / 6,265
11    35    31    42    12    53    18    6     5622  21    0.0391386  229 / 5,851
13    10    5     39    73    17    1     84    19    5688  0.0438729  261 / 5,949
5931  6733  6103  6072  5855  5405  5938  6313  5785  5865  0.0282333  1,694 / 60,000

Top-10 Hit Ratios:
k    hit_ratio
---  -----------
1    0.971767
2    0.992317
3    0.997
4    0.9986
5    0.99925
6    0.999633
7    0.9998
8    0.999917
9    0.999967
10   1

In [60]:
# Validation set metrics
valid_perf = model.model_performance(test)
print("Validation performance: ", valid_perf)

Validation performance:  ModelMetricsMultinomial: deeplearning
** Reported on test data. **

MSE: 0.028610970731963618
RMSE: 0.1691477777919758
LogLoss: 0.11646824606917394
Mean Per-Class Error: 0.03300755699704586
AUC table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).
AUCPR table was not computed: it is either disabled (model parameter 'auc_type' was set to AUTO or NONE) or the domain size exceeds the limit (maximum is 50 domains).

Confusion Matrix: Row labels: Actual class; Column labels: Predicted class
0    1     2     3     4    5    6    7     8    9    Error       Rate
---  ----  ----  ----  ---  ---  ---  ----  ---  ---  ----------  ------------
968  0     1     2     1    2    3    1     2    0    0.0122449   12 / 980
0    1125  6     0     0    0    3    0     1    0    0.00881057  10 / 1,135
6    1     994   8     4    0    4    8     5    2    0.0368217   38 / 1,032
0    0     11    976   0    6    1    9     7    0    0.0336634   34 / 1,010
1    0     7     0     947  0    11   3     3    10   0.0356415   35 / 982
3    0     2     16    2    850  7    1     9    2    0.0470852   42 / 892
8    3     1     1     6    5    932  0     2    0    0.0271399   26 / 958
2    6     13    2     1    0    0    993   0    11   0.0340467   35 / 1,028
3    1     6     7     3    10   3    7     933  1    0.0420945   41 / 974
5    6     1     10    18   0    0    11    2    956  0.0525273   53 / 1,009
996  1142  1042  1022  982  873  964  1033  964  982  0.0326      326 / 10,000

Top-10 Hit Ratios:
k    hit_ratio
---  -----------
1    0.9674
2    0.9889
3    0.9948
4    0.9981
5    0.9991
6    0.9994
7    0.9996
8    0.9997
9    0.9999
10   1

In [66]:
# Get MSE only for validation set
mse_valid = valid_perf.mse()
print("Validation MSE: ", mse_valid)

Validation MSE:  0.028610970731963618

In [62]:
# Variable importance
var_importance = model.varimp()
print("Variable importance: ", var_importance)

Variable importance:  [('C76', 1.0, 1.0, 0.0029891531397159402), ('C78', 0.9820566177368164, 0.9820566177368164, 0.0029355176222868214), ('C77', 0.9753942489624023, 0.9753942489624023, 0.0029156027817468363), ('C770', 0.9691189527511597, 0.9691189527511597, 0.0028968449603743525), ('C769', 0.9617758989334106, 0.9617758989334106, 0.002874895447999925), ('C768', 0.9557488560676575, 0.9557488560676575, 0.0028568796938945565), ('C773', 0.949530839920044, 0.949530839920044, 0.002838293091404113), ('C75', 0.9327151775360107, 0.9327151775360107, 0.002788028501392477), ('C771', 0.8955176472663879, 0.8955176472663879, 0.002676839386997355), ('C772', 0.8902101516723633, 0.8902101516723633, 0.0026609744698784478), ('C295', 0.885613203048706, 0.885613203048706, 0.0026472334864669302), ('C767', 0.8789734840393066, 0.8789734840393066, 0.002627386349543152), ('C323', 0.8760762214660645, 0.8760762214660645, 0.0026187259880257638), ('C774', 0.862788736820221, 0.862788736820221, 0.0025790076615777135), ('C74', 0.8499899506568909, 0.8499899506568909, 0.0025407501297330425), ('C283', 0.8384130597114563, 0.8384130597114563, 0.0025061450298153477), ('C586', 0.8116911053657532, 0.8116911053657532, 0.002426269016083543), ('C766', 0.8086795210838318, 0.8086795210838318, 0.0024172669294717187), ('C351', 0.7987663149833679, 0.7987663149833679, 0.0023876348383318658), ('C255', 0.7957316637039185, 0.7957316637039185, 0.0023785638009319564), ('C322', 0.7944291234016418, 0.7944291234016418, 0.0023746703084977995), ('C73', 0.7930260300636292, 0.7930260300636292, 0.0023704762476411644), ('C79', 0.7903978228569031, 0.7903978228569031, 0.0023626201338173554), ('C349', 0.7861368060112, 0.7861368060112, 0.0023498833019346393), ('C517', 0.7856523394584656, 0.7856523394584656, 0.002348435157217446), ('C294', 0.7809338569641113, 0.7809338569641113, 0.0023343308904547524), ('C348', 0.7798932790756226, 0.7798932790756226, 0.002331220443792257), ('C350', 0.779802143573761, 0.779802143573761, 0.0023309480258207277), ('C321', 0.7781866192817688, 0.7781866192817688, 0.0023261189763110323), ('C267', 0.7713404893875122, 0.7713404893875122, 0.002305654845642712), ('C544', 0.7695543169975281, 0.7695543169975281, 0.0023003157028351168), ('C377', 0.7568181157112122, 0.7568181157112122, 0.0022622452467720715), ('C227', 0.7564691305160522, 0.7564691305160522, 0.0022612020765802447), ('C434', 0.7537291049957275, 0.7537291049957275, 0.0022530117206932643), ('C297', 0.7460497617721558, 0.7460497617721558, 0.0022300569877855684), ('C378', 0.7442562580108643, 0.7442562580108643, 0.0022246959303864116), ('C545', 0.7427575588226318, 0.7427575588226318, 0.002220216089002417), ('C558', 0.7376387715339661, 0.7376387715339661, 0.0022049152499069636), ('C531', 0.7371631860733032, 0.7371631860733032, 0.00220349365213402), ('C461', 0.7364164590835571, 0.7364164590835571, 0.00220126157080811), ('C559', 0.7355115413665771, 0.7355115413665771, 0.0021985566331732148), ('C462', 0.7350916266441345, 0.7350916266441345, 0.0021973014437622123), ('C488', 0.7343606948852539, 0.7343606948852539, 0.002195116576800236), ('C404', 0.7342735528945923, 0.7342735528945923, 0.002194856096045249), ('C324', 0.7327385544776917, 0.7327385544776917, 0.0021902677507079113), ('C268', 0.7327225208282471, 0.7327225208282471, 0.002190219823674333), ('C741', 0.7304666042327881, 0.7304666042327881, 0.0021834765435000793), ('C489', 0.7285370826721191, 0.7285370826721191, 0.002177708908068856), ('C266', 0.7246974110603333, 0.7246974110603333, 0.0021662315416150083), ('C311', 0.722743570804596, 0.722743570804596, 0.002160391213880068), ('C614', 0.7207807302474976, 0.7207807302474976, 0.0021545239828660552), ('C72', 0.7154187560081482, 0.7154187560081482, 0.002138496220733428), ('C775', 0.7145037055015564, 0.7145037055015564, 0.0021357609946386505), ('C68', 0.7126161456108093, 0.7126161456108093, 0.002130118789064822), ('C490', 0.7070082426071167, 0.7070082426071167, 0.002113355908194112), ('C352', 0.7069413065910339, 0.7069413065910339, 0.002113155826191478), ('C591', 0.7069308161735535, 0.7069308161735535, 0.0021131244687271292), ('C40', 0.7047800421714783, 0.7047800421714783, 0.0021066954758660068), ('C296', 0.703884482383728, 0.703884482383728, 0.00210401851051465), ('C460', 0.7002944946289062, 0.7002944946289062, 0.0020932874873457828), ('C293', 0.7000100016593933, 0.7000100016593933, 0.002092437094292736), ('C270', 0.6997888684272766, 0.6997888684272766, 0.002091776093197659), ('C486', 0.699370801448822, 0.699370801448822, 0.0020905264269763997), ('C648', 0.6986808776855469, 0.6986808776855469, 0.002088464139193241), ('C41', 0.6973545551300049, 0.6973545551300049, 0.002084499557962067), ('C516', 0.6963346004486084, 0.6963346004486084, 0.0020814507572238026), ('C298', 0.6962615847587585, 0.6962615847587585, 0.002081232502145239), ('C619', 0.6946426033973694, 0.6946426033973694, 0.002076393118925701), ('C518', 0.6945183277130127, 0.6945183277130127, 0.0020760216398736163), ('C380', 0.6944782137870789, 0.6944782137870789, 0.0020759017332059645), ('C71', 0.6942738890647888, 0.6942738890647888, 0.00207529097532081), ('C318', 0.693250298500061, 0.693250298500061, 0.00207223130637047), ('C515', 0.6925070285797119, 0.6925070285797119, 0.002070009558754402), ('C376', 0.691497266292572, 0.691497266292572, 0.0020669912246434313), ('C405', 0.6905931234359741, 0.6905931234359741, 0.0020642886031848797), ('C563', 0.6891143918037415, 0.6891143918037415, 0.0020598684478835942), ('C407', 0.6866261959075928, 0.6866261959075928, 0.002052430849308393), ('C325', 0.686565101146698, 0.686565101146698, 0.002052248227712044), ('C65', 0.6843201518058777, 0.6843201518058777, 0.002045537730341428), ('C406', 0.6831568479537964, 0.6831568479537964, 0.0020420604369795355), ('C379', 0.6828716397285461, 0.6828716397285461, 0.002041207905917556), ('C69', 0.6824579238891602, 0.6824579238891602, 0.002039971245917305), ('C320', 0.6816110610961914, 0.6816110610961914, 0.002037439843340794), ('C742', 0.6815420389175415, 0.6815420389175415, 0.0020372335254787727), ('C347', 0.6791771054267883, 0.6791771054267883, 0.0020301643771096682), ('C435', 0.6791644096374512, 0.6791644096374512, 0.00203012642745111), ('C491', 0.6774566769599915, 0.6774566769599915, 0.002025021752956486), ('C487', 0.6773952841758728, 0.6773952841758728, 0.0020248382405230816), ('C457', 0.6731691360473633, 0.6731691360473633, 0.002012205636575843), ('C42', 0.6723542213439941, 0.6723542213439941, 0.0020097697317316664), ('C375', 0.6680207848548889, 0.6680207848548889, 0.0019968164264444976), ('C463', 0.6678566336631775, 0.6678566336631775, 0.001996325753394405), ('C269', 0.6670966744422913, 0.6670966744422913, 0.0019940541189032374), ('C587', 0.6668574213981628, 0.6668574213981628, 0.001993338954915194), ('C70', 0.6627289056777954, 0.6627289056777954, 0.001980998189187291), ('C354', 0.6618592143058777, 0.6618592143058777, 0.0019783985484923394), ('C212', 0.6608418226242065, 0.6608418226242065, 0.0019753574089527515), ('C43', 0.6608380675315857, 0.6608380675315857, 0.0019753461844058537), ('C739', 0.6603715419769287, 0.6603715419769287, 0.0019739516680793933), ('C543', 0.6602848172187805, 0.6602848172187805, 0.0019736924344962836), ('C737', 0.6600018739700317, 0.6600018739700317, 0.0019728466737959248), ('C458', 0.6594876050949097, 0.6594876050949097, 0.0019713094453731954), ('C339', 0.6590110063552856, 0.6590110063552856, 0.0019698848187542635), ('C738', 0.6564621329307556, 0.6564621329307556, 0.001962265845754591), ('C401', 0.6563789248466492, 0.6563789248466492, 0.0019620171240487343), ('C292', 0.6561601161956787, 0.6561601161956787, 0.001961363071482689), ('C291', 0.6550030708312988, 0.6550030708312988, 0.0019579044856989592), ('C271', 0.6541711688041687, 0.6541711688041687, 0.001955417803142627), ('C432', 0.6541112661361694, 0.6541112661361694, 0.0019552387448944996), ('C433', 0.6538531184196472, 0.6538531184196472, 0.001954467101837147), ('C67', 0.6508954763412476, 0.6508954763412476, 0.0019456262567323426), ('C299', 0.6494391560554504, 0.6494391560554504, 0.00194127309237762), ('C353', 0.6492404341697693, 0.6492404341697693, 0.001940679082229106), ('C66', 0.6488902568817139, 0.6488902568817139, 0.0019396323486890578), ('C300', 0.6486284732818604, 0.6486284732818604, 0.0019388498374196296), ('C319', 0.645396888256073, 0.645396888256073, 0.0019291901348935383), ('C211', 0.645363986492157, 0.645363986492157, 0.0019290917864826266), ('C765', 0.6438943147659302, 0.6438943147659302, 0.001924698712627824), ('C507', 0.6415390372276306, 0.6415390372276306, 0.0019176584273793134), ('C402', 0.6414840221405029, 0.6414840221405029, 0.001917493978858894), ('C503', 0.6405007839202881, 0.6405007839202881, 0.00191455492924585), ('C272', 0.6386148929595947, 0.6386148929595947, 0.0019089177123595316), ('C744', 0.637195348739624, 0.637195348739624, 0.0019046744772974406), ('C571', 0.6370922923088074, 0.6370922923088074, 0.0019043664258436971), ('C546', 0.6359848380088806, 0.6359848380088806, 0.001901056075345979), ('C381', 0.6358888745307922, 0.6358888745307922, 0.001900769225814153), ('C264', 0.6322059035301208, 0.6322059035301208, 0.0018897602614840134), ('C475', 0.6321503520011902, 0.6321503520011902, 0.0018895942094568944), ('C535', 0.6303590536117554, 0.6303590536117554, 0.0018842397442519472), ('C403', 0.6295905113220215, 0.6295905113220215, 0.0018819424536535847), ('C214', 0.6295578479766846, 0.6295578479766846, 0.0018818448179123172), ('C642', 0.6294638514518738, 0.6294638514518738, 0.0018815638479050567), ('C408', 0.6286166906356812, 0.6286166906356812, 0.00187903155449149), ('C431', 0.6281102895736694, 0.6281102895736694, 0.0018775178441670223), ('C301', 0.6278976202011108, 0.6278976202011108, 0.0018768821428443174), ('C239', 0.6271445155143738, 0.6271445155143738, 0.0018746309976054225), ('C438', 0.6263587474822998, 0.6263587474822998, 0.0018722822166252601), ('C265', 0.6245614886283875, 0.6245614886283875, 0.0018669099346792057), ('C743', 0.6237787008285522, 0.6237787008285522, 0.001864570062069597), ('C326', 0.6201508045196533, 0.6201508045196533, 0.001853725724427288), ('C736', 0.6200875043869019, 0.6200875043869019, 0.0018535365106367295), ('C492', 0.619583785533905, 0.619583785533905, 0.0018520308178457598), ('C238', 0.619019091129303, 0.619019091129303, 0.0018503428597932635), ('C740', 0.6189512610435486, 0.6189512610435486, 0.0018501401052794637), ('C327', 0.6149371862411499, 0.6149371862411499, 0.001838141420980819), ('C459', 0.6147732734680176, 0.6147732734680176, 0.001837651460600371), ('C400', 0.6147670149803162, 0.6147670149803162, 0.0018376327530222085), ('C437', 0.6135401725769043, 0.6135401725769043, 0.001833965533200113), ('C430', 0.6134955883026123, 0.6134955883026123, 0.0018338322639766312), ('C514', 0.6113967299461365, 0.6113967299461365, 0.0018275584549305526), ('C210', 0.6113187670707703, 0.6113187670707703, 0.0018273254119568704), ('C372', 0.6109514236450195, 0.6109514236450195, 0.0018262273662024335), ('C573', 0.6079283356666565, 0.6079283356666565, 0.0018171908932802722), ('C676', 0.6077137589454651, 0.6077137589454651, 0.001816549490600413), ('C374', 0.6076685190200806, 0.6076685190200806, 0.0018164142615354094), ('C184', 0.6070764064788818, 0.6070764064788818, 0.00181464434647382), ('C485', 0.606459379196167, 0.606459379196167, 0.0018127999574344025), ('C464', 0.6041695475578308, 0.6041695475578308, 0.001805955300003249), ('C542', 0.6031551361083984, 0.6031551361083984, 0.0018029230688342143), ('C242', 0.6029035449028015, 0.6029035449028015, 0.0018021710241920793), ('C356', 0.5995734930038452, 0.5995734930038452, 0.0017922169891028971), ('C183', 0.597555935382843, 0.597555935382843, 0.0017861862004055207), ('C345', 0.5966416001319885, 0.5966416001319885, 0.0017834531123196759), ('C64', 0.5958846211433411, 0.5958846211433411, 0.0017811903861990614), ('C572', 0.5958481431007385, 0.5958481431007385, 0.0017810813477434854), ('C241', 0.5957252383232117, 0.5957252383232117, 0.0017807139665418548), ('C243', 0.5941584706306458, 0.5941584706306458, 0.001776030657974416), ('C240', 0.5940331816673279, 0.5940331816673279, 0.0017756561500763424), ('C185', 0.5927535891532898, 0.5927535891532898, 0.0017718312520954487), ('C429', 0.5919932126998901, 0.5919932126998901, 0.001769558370432403), ('C465', 0.5901782512664795, 0.5901782512664795, 0.0017641331727652602), ('C576', 0.5891281366348267, 0.5891281366348267, 0.0017609942193169935), ('C182', 0.5890699028968811, 0.5890699028968811, 0.001760820149756376), ('C195', 0.5888911485671997, 0.5888911485671997, 0.0017602858256905711), ('C519', 0.5882500410079956, 0.5882500410079956, 0.0017583694570170805), ('C215', 0.5877542495727539, 0.5877542495727539, 0.0017568874604917835), ('C344', 0.5867510437965393, 0.5867510437965393, 0.0017538887247960306), ('C91', 0.5866878032684326, 0.5866878032684326, 0.001753699689172883), ('C330', 0.5864601731300354, 0.5864601731300354, 0.001753019267829999), ('C447', 0.5861455202102661, 0.5861455202102661, 0.0017520787220669499), ('C92', 0.5852554440498352, 0.5852554440498352, 0.0017494181481174115), ('C213', 0.5845251083374023, 0.5845251083374023, 0.0017472350628295462), ('C167', 0.5834993124008179, 0.5834993124008179, 0.001744168801684997), ('C317', 0.5834505558013916, 0.5834505558013916, 0.00174402306074274), ('C360', 0.58294278383255, 0.58294278383255, 0.0017425052525678175), ('C216', 0.5822970867156982, 0.5822970867156982, 0.0017405751650036744), ('C436', 0.5817092061042786, 0.5817092061042786, 0.001738817899828271), ('C244', 0.5808866024017334, 0.5808866024017334, 0.0017363590113880663), ('C409', 0.5806947350502014, 0.5806947350502014, 0.0017357854904918254), ('C328', 0.5805470943450928, 0.5805470943450928, 0.0017353441698146), ('C592', 0.5803356170654297, 0.5803356170654297, 0.0017347120318401167), ('C237', 0.5784898996353149, 0.5784898996353149, 0.0017291948997888607), ('C620', 0.5765164494514465, 0.5765164494514465, 0.0017232959549756774), ('C466', 0.574228048324585, 0.574228048324585, 0.0017164555735623896), ('C530', 0.5725867748260498, 0.5725867748260498, 0.0017115495557311108), ('C39', 0.5724884271621704, 0.5724884271621704, 0.001711255579502842), ('C548', 0.5717858672142029, 0.5717858672142029, 0.0017091555202285362), ('C289', 0.5700337886810303, 0.5700337886810303, 0.0017039182891800744), ('C541', 0.5699728727340698, 0.5699728727340698, 0.0017037362020859588), ('C263', 0.5697348713874817, 0.5697348713874817, 0.0017030247796135482), ('C236', 0.5688046813011169, 0.5688046813011169, 0.0017002442989963583), ('C329', 0.567817211151123, 0.567817211151123, 0.0016972925994971284), ('C547', 0.5677396059036255, 0.5677396059036255, 0.0016970606255279127), ('C745', 0.566068172454834, 0.566068172454834, 0.0016920644549866311), ('C46', 0.5655182600021362, 0.5655182600021362, 0.001690420682452081), ('C290', 0.5651987791061401, 0.5651987791061401, 0.001689465705128735), ('C355', 0.5638038516044617, 0.5638038516044617, 0.0016852960532074165), ('C513', 0.5634739398956299, 0.5634739398956299, 0.001684309896587133), ('C93', 0.5630224347114563, 0.5630224347114563, 0.0016829602784482625), ('C99', 0.562898576259613, 0.562898576259613, 0.0016825900465680548), ('C359', 0.5611225962638855, 0.5611225962638855, 0.001677281370387753), ('C373', 0.5605043768882751, 0.5605043768882751, 0.0016754334180001142), ('C223', 0.5595462918281555, 0.5595462918281555, 0.0016725695550345427), ('C251', 0.5573464632034302, 0.5573464632034302, 0.001665993930394108), ('C187', 0.5567128658294678, 0.5567128658294678, 0.0016641000108144125), ('C346', 0.5567046999931335, 0.5567046999931335, 0.0016640756018790957), ('C484', 0.556428849697113, 0.556428849697113, 0.0016632510431006543), ('C570', 0.5555927157402039, 0.5555927157402039, 0.001660751710658136), ('C156', 0.5549294948577881, 0.5549294948577881, 0.0016587692418751378), ('C262', 0.554250955581665, 0.554250955581665, 0.001656740984067494), ('C209', 0.5539295673370361, 0.5539295673370361, 0.0016557803053869938), ('C101', 0.5538924932479858, 0.5538924932479858, 0.001655669485257307), ('C428', 0.5535326600074768, 0.5535326600074768, 0.0016545938885966652), ('C647', 0.553267776966095, 0.553267776966095, 0.0016538021126218613), ('C45', 0.5526260733604431, 0.5526260733604431, 0.0016518839622742599), ('C735', 0.5520618557929993, 0.5520618557929993, 0.0016501974295610523), ('C44', 0.551618218421936, 0.551618218421936, 0.0016488713295204434), ('C574', 0.5507161617279053, 0.5507161617279053, 0.0016461749439212795), ('C520', 0.5502263307571411, 0.5502263307571411, 0.0016447107641370897), ('C97', 0.5491915345191956, 0.5491915345191956, 0.0016416175997134685), ('C98', 0.5479633212089539, 0.5479633212089539, 0.0016379462820409185), ('C186', 0.5456880927085876, 0.5456880927085876, 0.0016311452756254778), ('C569', 0.545155942440033, 0.545155942440033, 0.001629554596979427), ('C658', 0.5431906580924988, 0.5431906580924988, 0.0016236800611015604), ('C512', 0.54264235496521, 0.54264235496521, 0.001622041099087109), ('C579', 0.5424957871437073, 0.5424957871437073, 0.0016216029854232829), ('C456', 0.5422098636627197, 0.5422098636627197, 0.0016207483163523705), ('C603', 0.5421460270881653, 0.5421460270881653, 0.0016205574990551122), ('C367', 0.5400614142417908, 0.5400614142417908, 0.0016143262720202797), ('C613', 0.5393019318580627, 0.5393019318580627, 0.0016120560628684), ('C410', 0.5392078161239624, 0.5392078161239624, 0.0016117747365263174), ('C95', 0.5389717817306519, 0.5389717817306519, 0.0016110691935784724), ('C181', 0.5383175611495972, 0.5383175611495972, 0.0016091136280745458), ('C302', 0.5380721092224121, 0.5380721092224121, 0.0016083799346757514), ('C47', 0.5371739864349365, 0.5371739864349365, 0.0016056953081257184), ('C470', 0.5366412401199341, 0.5366412401199341, 0.0016041028478055567), ('C208', 0.5365827083587646, 0.5365827083587646, 0.001603927887407884), ('C764', 0.5360564589500427, 0.5360564589500427, 0.001602354847335529), ('C712', 0.5355040431022644, 0.5355040431022644, 0.0016007035917697137), ('C316', 0.5345743298530579, 0.5345743298530579, 0.0015979245364918125), ('C657', 0.5340927243232727, 0.5340927243232727, 0.0015964849438103506), ('C577', 0.5333358645439148, 0.5333358645439148, 0.0015942225740245583), ('C155', 0.53294438123703, 0.53294438123703, 0.0015930523704686373), ('C235', 0.5325883626937866, 0.5325883626937866, 0.001591988176522304), ('C483', 0.532541036605835, 0.532541036605835, 0.001591846711597913), ('C493', 0.5319425463676453, 0.5319425463676453, 0.001590057732623339), ('C575', 0.5319389700889587, 0.5319389700889587, 0.0015900470425786746), ('C746', 0.5316088199615479, 0.5316088199615479, 0.0015890601732887466), ('C511', 0.5313801169395447, 0.5313801169395447, 0.0015883765449324634), ('C399', 0.5312007665634155, 0.5312007665634155, 0.0015878404391925476), ('C540', 0.5307958126068115, 0.5307958126068115, 0.0015866299698017244), ('C641', 0.529640257358551, 0.529640257358551, 0.0015831758382032714), ('C279', 0.5295641422271729, 0.5295641422271729, 0.0015829483184193324), ('C157', 0.5294779539108276, 0.5294779539108276, 0.0015826906883429223), ('C585', 0.5290560126304626, 0.5290560126304626, 0.0015814294412399435), ('C602', 0.5289267897605896, 0.5289267897605896, 0.0015810431742927394), ('C80', 0.5274394154548645, 0.5274394154548645, 0.0015765971847168483), ('C343', 0.5273633003234863, 0.5273633003234863, 0.0015763696649329093), ('C495', 0.5272834897041321, 0.5272834897041321, 0.001576131098769484), ('C273', 0.5258544683456421, 0.5258544683456421, 0.0015718595350890324), ('C387', 0.5254927277565002, 0.5254927277565002, 0.0015707782370712364), ('C180', 0.5250012874603271, 0.5250012874603271, 0.0015693092467669477), ('C158', 0.5249188542366028, 0.5249188542366028, 0.0015690628412374352), ('C382', 0.524329662322998, 0.524329662322998, 0.0015673016563789882), ('C686', 0.5240523815155029, 0.5240523815155029, 0.0015664728215826812), ('C331', 0.5226954221725464, 0.5226954221725464, 0.0015624166623022157), ('C494', 0.5210068821907043, 0.5210068821907043, 0.0015573693577139568), 

In [63]:
# Predictions
pred = model.predict(test)
print("Predictions: ", pred.head())

deeplearning prediction progress: |██████████████████████████████████████████████| (done) 100%
Predictions:    predict           p0           p1           p2           p3           p4           p5           p6           p7           p8           p9
        8  1.11273e-08  6.22812e-07  9.90168e-07  7.03138e-06  4.21413e-08  2.77153e-06  9.31764e-08  8.1077e-09   0.999987     1.64006e-06
        3  6.05483e-11  3.72786e-08  3.98553e-08  0.999984     4.27197e-10  1.06254e-06  2.81699e-12  1.19649e-06  6.02361e-06  7.65789e-06
        8  0.0812754    0.000508378  0.0128297    0.00772221   0.00496229   0.0985099    0.213177     0.000675486  0.574423     0.00591656
        0  0.997569     2.70662e-08  3.42211e-06  2.442e-07    1.13628e-06  5.87922e-06  0.00241297   2.83724e-07  4.99578e-06  2.52263e-06
        1  7.34495e-11  0.999999     3.47374e-08  1.37428e-08  9.21581e-08  2.21371e-09  1.08854e-08  2.22102e-07  3.51128e-07  1.77772e-08
        5  1.61587e-05  1.69459e-05  2.37344e-05  0.000264944  1.42874e-05  0.878512     0.000117538  1.79895e-05  0.12077      0.000246743
        0  1            2.48509e-13  1.62541e-09  5.19848e-10  3.10565e-11  1.70148e-08  8.90212e-09  8.1043e-09   1.60291e-08  7.39611e-08
        1  1.88692e-10  0.999996     4.79013e-08  2.95513e-08  6.58078e-07  1.48631e-09  5.82922e-09  1.86436e-06  1.04168e-06  1.32208e-07
        5  7.75405e-08  1.10355e-06  7.43423e-07  0.0128555    4.96913e-07  0.986844     9.59526e-06  5.82855e-08  0.000116353  0.000172325
        2  3.28279e-06  0.000205943  0.997005     0.00147778   8.82113e-07  4.34609e-05  1.02301e-05  0.000796683  0.000456332  8.85802e-07
[10 rows x 11 columns]

In [64]:
from h2o.grid.grid_search import H2OGridSearch

# Define hyperparameters for grid search
hidden_opt = [[100, 300, 100], [500, 500, 500]]
l1_opt = [1e-5, 1e-7]
hyper_params = {'hidden': hidden_opt, 'l1': l1_opt}

# Define search criteria
search_criteria = {'strategy': 'RandomDiscrete', 'max_runtime_secs': 900}

# Perform grid search
model_grid = H2OGridSearch(
    model=H2ODeepLearningEstimator(
        distribution='multinomial',
        epochs=5,
        validation_frame=test
    ),
    hyper_params=hyper_params,
    search_criteria=search_criteria
)

model_grid.train(x=x, y=y, training_frame=train)

# Print out all prediction errors of the models
print(model_grid)

deeplearning Grid Build progress: |██████████████████████████████████████████████| (done) 100%
Hyper-Parameter Search Summary: ordered by increasing logloss
    hidden           l1     model_ids                                                               logloss
--  ---------------  -----  ----------------------------------------------------------------------  ---------
    [500, 500, 500]  1e-07  Grid_DeepLearning_py_33_sid_a081_model_python_1717403639876_66_model_1  0.168967

In [65]:
# Print out the Test MSE for all of the models
for model_id in model_grid.model_ids:
    model = h2o.get_model(model_id)
    mse = model.model_performance(valid=True).mse()
    print(f"Model ID: {model_id}, Test set MSE: {mse:.6f}")

Model ID: Grid_DeepLearning_py_33_sid_a081_model_python_1717403639876_66_model_1, Test set MSE: 0.030876

In [67]:
h2o.cluster().shutdown()

H2O session _sid_a081 closed.

<ipython-input-67-1edf85295eae>:1: H2ODeprecationWarning: Deprecated, use ``h2o.cluster().shutdown()``.
  h2o.shutdown()

# Exercise (Titanic): 45 minutes

[Kaggle](https://www.kaggle.com/competitions/titanic)