In [1]:
import pandas as pd

obecnie najnowsza stabilna wersja pandasa jest 2.3. Wkrotce pojawi sie pandas 3.0 (narazie jest w wersji dev)
kozystajac z pliku requiraments_p3.txt mozemy stworzyc dodatkowe srodowisko z zainstalowana dev wersja padanas 3.0 i porownac dzialanie z pandasem 2.3

Przypomnienie: 
* aby stworzyc nowe srodowisko uzywamy polecenia:
    ```
    python -m venv <root katalogu projektu>/nazwasrodowiska
    ```
* aby aktywowac srodowisko:
    - na Windows:
            ```
            <root katalogu projektu>\nazwasrodowiska\Scripts\activate.<bat/ps1>    
            ```
    - na macOS/Linux:
            ```
            source <root katalogu projektu>/nazwasrodowiska/bin/activate
            ```

* aby zainstalowac pakiety z pliku requirements.txt uzywamy polecenia:
    ```
    pip install -r requirements.txt
    ```

Aby wybrac srodowisko w VSCode, naciskamy `Cmd+Shift+P` (macOS) lub `Ctrl+Shift+P` (Windows/Linux) i wybieramy `Python: Select Interpreter`, a nastepnie wybieramy srodowisko, ktore wlasnie stworzylysmy. LUB w prawym gornym rogu okna VSCode klikamy na nazwe aktualnie wybranego interpretera Pythona (lub **Select Kernel** ) i wybieramy srodowisko, ktore wlasnie stworzylysmy.

aby sprawdzic wersje pandasa: 
`pd.__version__`

In [2]:
pd.__version__ 
## zwraca 2.3.3 dla aiw_py3.13

## zwraca '3.0.0rc0' dla srodowiska venv_pandas3

'3.0.0rc0'

In [3]:
# tworzenie DataFrame z listy 2-wymiarowej. Kazdy wiersz to wiersz w DataFrame.
data = [[1,'a'],
[2, 'b'],
[3, 'c']]

df = pd.DataFrame(data)
display(df)

# pandas domyslnie nadaje indeks i nazwy kolumn
# mozemy rowniez podac kolumni lub indeks w parametrach:

df = pd.DataFrame(data, columns=['id', 'nazwa'])
display(df)

df = pd.DataFrame(data, columns=['id', 'nazwa'], index=['A1', 'A2', 'A3'])
display(df)

   0  1
0  1  a
1  2  b
2  3  c

   id nazwa
0   1     a
1   2     b
2   3     c

    id nazwa
A1   1     a
A2   2     b
A3   3     c

In [4]:
## pandas automatycznie dobiera typy danych: 
df.info()

## ------------------------------------------------------------------
## Rezultat dla pandas 2.3:
# <class 'pandas.core.frame.DataFrame'>
# Index: 3 entries, A1 to A3
# Data columns (total 2 columns):
#  #   Column  Non-Null Count  Dtype 
# ---  ------  --------------  ----- 
#  0   id      3 non-null      int64 
#  1   nazwa   3 non-null      object
# dtypes: int64(1), object(1)
# memory usage: 72.0+ bytes

## ------------------------------------------------------------------
## Rezultat dla pandas 3.0
# <class 'pandas.DataFrame'>
# Index: 3 entries, A1 to A3
# Data columns (total 2 columns):
#  #   Column  Non-Null Count  Dtype
# ---  ------  --------------  -----
#  0   id      3 non-null      int64
#  1   nazwa   3 non-null      str  
# dtypes: int64(1), str(1)
# memory usage: 72.0+ bytes

## ------------------------------------------------------------------
# ROZNICE:
# - kolumna nazwa w pandas 2.3 ma typ object, a w 3.0 typ 'str'

<class 'pandas.DataFrame'>
Index: 3 entries, A1 to A3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      3 non-null      int64
 1   nazwa   3 non-null      str
dtypes: int64(1), str(1)
memory usage: 72.0+ bytes

In [5]:
## konsekwencje zmiany typu:

# ponizsza komenda zmienia wartosc dla "nazwa" w wierszu "A3" dataFrame: w pandas3.0 zwroci blad
# "TypeError: Invalid value '5' for dtype 'str'. Value should be a string or missing value, got 'int' instead."
# ale zadziala dla pandas2.3

df.loc['A3'] = [4, 5]

TypeError: Invalid value '5' for dtype 'str'. Value should be a string or missing value, got 'int' instead.

In [7]:
# jezeli sprobujemy dodac analogiczny wiersz w pandas3.0 kolumna nazwa zmienie typ ze string na object
print("typ PRZED dodaniem wiesza: ")
print(df.info())

df.loc['A4'] = [4, 5] 
print("-----------------------------------------")
print("typ PO dodaniem wiesza: ")
print(df.info())

typ PRZED dodaniem wiesza:
<class 'pandas.DataFrame'>
Index: 4 entries, A1 to A4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      4 non-null      int64
 1   nazwa   4 non-null      object
dtypes: int64(1), object(1)
memory usage: 96.0+ bytes
None
-----------------------------------------
typ PO dodaniem wiesza:
<class 'pandas.DataFrame'>
Index: 4 entries, A1 to A4
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      4 non-null      int64
 1   nazwa   4 non-null      object
dtypes: int64(1), object(1)
memory usage: 268.0+ bytes
None

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, A1 to A3
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   id      3 non-null      int64
 1   nazwa   3 non-null      object
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes